### ISSUE TITLE
Only 30 comments shown for an issue on the webcompat site

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1044]
Compare the number of comments shown here: 
https://github.com/webcompat/web-bugs/issues/1470
and here:
https://webcompat.com/issues/1470

The webcompat site seems to show only the first 30 or so.

**Comment by hallvors** [comment]
https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue - probably some paging built-into the API, note how the example shows LINK rel=next header..

**Comment by miketaylr** [comment]
Yeah, just had that same thought. Shouldn't be very hard to fix, thanks @hallvors.

**Comment by miketaylr** [comment]
So, a couple of different ways we could fix this:

1. At the API (server) level. If we detect pagination, we request until the last page, lump all the comments into a single response and serve that to the client.

3. At the client level. Similar to option 1, but we do it with JS. Not sure there's any benefit, because comments are loaded after we render everything else.

2. At the client level. We can lazily load comments 31+ after initial page load. Downside is if you tried to bookmark a comment that hasn't been loaded yet, it won't work the way you intended it to.

@karlcow thoughts?

**Comment by miketaylr** [comment]
(I kinda feel like the first option is the way to go, but open to other ideas)

**Comment by adamopenweb** [comment]
@miketaylr #1 sounds best. Do you think it will increase load times? (I'm guessing this scenario doesn't happen very often)

**Comment by miketaylr** [comment]
@adamopenweb Thanks. It might a bit -- but it should only do that for issues with more comments (which as you say, it pretty rare).

I also thought of a cheap hack, we can actually request up to 100 comments at a time. So we can do a quick band-aid fix and then maybe our Outreachy participant can work on the "good" fix. :)

**Comment by miketaylr** [comment]
Lazy hack: https://developer.github.com/guides/traversing-with-pagination/#changing-the-number-of-items-received
