### ISSUE TITLE
 Functional tests for file upload screenshots

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1047]
The other half to #1043.

**Comment by miketaylr** [comment]
I'm pretty sure we have this now.

**Comment by miketaylr** [comment]
> I'm pretty sure we have this now.

Tsk, tsk. We don't.

To fix this, we need to write tests around actually uploading an image (one of our green.png fixture files is fine) and making sure they do the same thing as the postMessage'd image:

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/image-uploads-non-auth.js

**Comment by brizental** [comment]
I would like to work on this.

**Comment by miketaylr** [comment]
Great! It should be helpful to have a look at existing tests, as well as https://theintern.github.io/leadfoot/index.html and http://chaijs.com/api/assert/.

**Comment by brizental** [comment]
Nice, thanks :)

So, just to straighten things out, we are talking here about writing functional tests to the uploading of screenshots to the comments of an issue, right?

![screenshot from 2017-03-05 00-43-35](https://cloud.githubusercontent.com/assets/25176023/23583169/ebf74c04-013c-11e7-97a0-0737d0ac950f.png)

If so, the tests won't all be the same as for the postMessage'd image, since the interaction is not really the same. It's much simpler, not as much feedback.

I was thinking that we would only need a test for checking if a blob or dataURI were uploaded. Am I right?

**Comment by miketaylr** [comment]
> So, just to straighten things out, we are talking here about writing functional tests to the uploading of screenshots to the comments of an issue, right?

Yeah, but also for http://webcompat.com/issues/new

> If so, the tests won't all be the same as for the postMessage'd image, since the interaction is not really the same. It's much simpler, not as much feedback.

You're right. It's not even possible to use `postMessage` on the comment uploads, that only works on the new issue bug form.

> I was thinking that we would only need a test for checking if a blob or dataURI were uploaded. Am I right?

Yeah, something like that. One way to do that is to verify that we got back a URL from the upload endpoint (seen in the comment body on success): `![Screenshot of the site issue](http://staging.webcompat.com/uploads/2017/3/732f8196-3b10-4310-ae55-c510445e4282.jpg)`

**Comment by brizental** [comment]
Great, thanks for the detailed feedback, Mike.
I will give this a go now :)
