### ISSUE TITLE
[feature] Repeated patterns in bogus reporting

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1061]
this is a kind of follow-up on #1054 
The reporter in this case is easy to identify. I was wondering if a combination of patterns such as clearly identical UA information, IP, etc. Could help us time to time enter into contact with the reporter. The mechanism in place is a route which would redirect the user to a view giving more information and inviting them to contact us. 

The activation of the the pattern would be made manually on per case basis. With a pattern list.

**Comment by miketaylr** [comment]
Really cool idea.

**Comment by miketaylr** [comment]
This also would have been useful when we were getting all the weird Facebook spam -- our solution was to disable fb.com and facebook.com, but that prevented people from reporting real issues. In the end, it turned out to be a specific individual and after FB stalking him and explaining to him why what he was doing was inappropriate, he stopped.

**Comment by miketaylr** [comment]
Let's close in favor of #694.
