### ISSUE TITLE
Language Support and Translation

### ISSUE THREAD

**Issue by Mayccoll** [webcompat/webcompat.com#109]
The ability to translate the interface into different languages.

**Comment by tagawa** [comment]
Just keeping this alive and hoping we can have a discussion at some point about the best l10n framework to use so we can start extracting strings.

**Comment by miketaylr** [comment]
Thanks, I think we should def. have a conversation in Whistler about this.

**Comment by tagawa** [comment]
For reference, [13 tips for making responsive web design multi-lingual](http://responsivenews.co.uk/post/123104512468/13-tips-for-making-responsive-web-design) written by BBC developers.

**Comment by karlcow** [comment]
A summary of the discussions at Whistler, so it's not forgotten.

We discussed about trying to do a first version of another language. 
Some of the issues we identified was how to handle the analysis of bugs where we do not know about the language. Proposing a UI which has been translated into the language is the first part. The second part being to be able to process the flow of bugs in other languages. Will we create more frustrations if we do not have the ability to handle them.

**Comment by zbraniecki** [comment]
btw. we released new version of l20n library (3.0.0), which is going to be used in Firefox OS and other apps. It's stable and we can recommend it.

**Comment by ioana-chiorean** [comment]
hey @karlcow so we won't implement l10n - did I get it right? Some thoughts:
* have the interface in own lang so people understand the process 0- but ask to file the bug in English (not sure how many non-en bugs we have now)
* let people add bugs in several languages (10-15 ) and have a direct contact for each lang to get support. (ex: when a bug in Romanian is filled I can be pinged and help with it)

Both seems hard to  implement at the moment as they do not depend on the team.

**Comment by karlcow** [comment]
@ioana-chiorean The easiest part is the implementation. The most difficult part is the social management of it. 

Once an issue has been recorded. These are the things which are happening.

1. Someone reads the bug, and understand the steps to reproduce and/or ask more details if not clear enough. The person tries to reproduce the bug.
2. Someone needs to then establish a diagnosis with regards to the source code and/or interactions on the Web site.
3. Then once the diagnosis has been done, someone needs to find contact information for the mentioned site. 
4. Contact through twitter, the form, a github account, etc. etc. 
4. Someone needs to follow-up on these. It means check if the issue has been resolved, re-test, and possibly restart the machine to find another contact if no answer the first time. 

It means that sometimes you need more than one person, not everyone has all the skills to do everything. AND that is the most important someone who's dedicated enough to **follow-up** on these. 

With the current English only setup as of now:

* 100+ new issues, not taken care of yet.
* 101 which needs a diagnosis.
* 106 which needs contact information.
* 118 which are contact ready, but not yet contacted. 
* 151 already contacted but need to be checked for resolution or find another contact.

This means that right now even in English we don't have enough dedicated volunteers to handle those. And there are people doing a lot of work around them.

Knowing the French community and its English understanding, I'm pretty sure having French would help but the issue is more about dealing with the flow after. What is happening if we open the gate for other languages and nobody is here to handle them. 

We have already bugs written in English for Japanese, Chinese, and French sites. And we have difficulties to find volunteers. For Japanese, Mozilla Japan is helping a lot. For Chinese sites, we haven't yet really found a very effective way to manage that through dedicated volunteers.

I'm pretty sure there are strategies where we could improve things but maybe we are not there yet. I guess making it easier for managing and handling the bugs first in English would help a lot. Personal Dashboards. We discussed that with @calexity in Portland. And I'm pretty sure this will come back again.

**Comment by Jobava** [comment]
I would recommend using gettext (.po and .pot files) as the underlying localization format since: there are ludicrously many tools for that already and it integrates well with Mozilla's most used web-based tools for now: Pootle and Pontoon.

L20n is nicer to implement probably (on the dev side), it adds a little more flexibility, but at the expense of complexity. L20n allows you to have less strings, but more complex syntax and not something a non-technical localizer can handle. Even a GUI tool has to express that complexity and it tends to be difficult.

**Comment by ioana-chiorean** [comment]
I do understand it @karlcow . Maybe we can promote it more within the volunteers ( local communities to inspire them to take some ownrship and web dev to help out) 
I can help with the - 151 already contacted but need to be checked for resolution or find another contact. - should I look at the resolved tag?

**Comment by karlcow** [comment]
Putting here if we need in the future.
https://github.com/derkan/flask-locale

**Comment by miketaylr** [comment]
We're going to close for now, since we don't have the resources to work on this right now. This would be amazing, and perhaps we can revisit in the future.

**Comment by karlcow** [comment]
see #1638 for a simpler discussion/proposal about this.
