### ISSUE TITLE
Feature req: /u/nnnn redirects to site URL

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1090]
Sometimes I type in the URL to a webcompat issue on mobile just to click the issue link (I know, I should use QR..). Here's a wish: What if typing webcompat.com/u/1 would just redirect directly to the URL issue 1 is about?

**Comment by hallvors** [comment]
(This is better done server-side I guess, but probably requires fetching all data about the issue)

**Comment by karlcow** [comment]
Basically you are asking to create another URL shortener. I wonder if we could do that through a `,` tool style ala W3C. See [http://www.w3.org/,](http://www.w3.org/,)

For example: `https://webcompat.com/issues/1,u` but I guess you want something minimal to type. In that case I'm not sure we win a lot with `https://webcompat.com/u/1`

But maybe the issue is better expressed by:

Given an issue number, how do I get the URL on my mobile with a minimal typing. I wonder if add-ons or awesome bar could solve this.
