### ISSUE TITLE
New labels for type of issues categorization

### ISSUE THREAD

**Issue by tsl143** [webcompat/webcompat.com#1178]
Following tags can help us to club/identify many similar issues
- **Layout Issue** - any thing related to placement of elements, but looks same on all browsers
- **No Video** - as the label name says video is not played.
- **Not mobile friendly** - Bugs like Desktop website on mobile, or website not optimized for mobile layout (I am not sure if we should include the user agent detection for Firefox failure in this or not )

(Continued from #1175 )

**Comment by miketaylr** [comment]
This brings up an interesting point -- we currently have similar types of categorization when you report a bug: 

<img width="435" alt="screen shot 2016-09-21 at 6 44 05 pm" src="https://cloud.githubusercontent.com/assets/67283/18722113/744bfa84-802b-11e6-8a86-3ab91d859dc9.png">

But that's just info in the bug report, we don't turn that into a label. Labels are nice because you can group them... thoughts @karlcow?

**Comment by karlcow** [comment]
Let's rewind a bit :)

1. we had a free form for describing the issue and we didn't have useful feedback to guess the issue
2. We added the categories to give us a sense of what was the issue for people not giving more information.

These categories are hints on what the user thinks the issue is. They are not always exact from our perspective.

We could indeed reuse this and do automatic tagging, but then it also means we need to manage this to recategorize. Probably we should do a couple of simulation exercises (on paper) or whiteboard (at our next meeting) to see how we manage this.

The tagging itself in the backend is easy.
The UI is the hard part to crack.

So that it becomes useful for people participating on analyzing contacting.

Reminder of Bugzilla, Tech Evangelism, we were using the following keys:

On the ~3300 bugs of Tech Evangelism, there are 5411 individual keywords. Some of them are not relevant to our project so I removed them. And I reordered a bit by category

## Where from
* 1459 country-TLD 

## Categories of issues
*   98 [js]
*   67 [webkitcss]
*   62 [css]
*  864 [serversniff]: sniffing on the server side
*  182 [clientsniff]: sniffing on the client side. JS
*   44 [video]
*    7 [lib-brightcove]
*    6 [m3u8]
*   11 [tier1]: site doesn't send the tier1 version
*   24 [wap]: site sends WAP version
*   13 [http]: issues with HTTP
*   10 [wptouch]: Library in wordpress which had UA sniffing failing on Firefox OS.
*    6 [apz-evangelism]: issues with the APZ (scrolling)


## Security: mixed content blocking
*   26 [mcb-ie]
*   20 [mcb-chrome]
*    8 [ssl]
*    8 [mcb]
*    7 [mcb-thirdparty-notified]
*    7 [mcb-no-contact]


## Process/Management

*  170 [uaoverride]: A UA override has been applied at a point.
*   76 [needscontact]
*  733 [sitewait]
*  563 [contactready]
*   61 [notcontactready]
*   31 [needsdiagnosis]
*   16 [needaccount]
*  223 [mobile-compat-form]: coming from the webcompat form directly
*   10 [bzlite]

**Comment by karlcow** [comment]
Probably we would want to move the process stuff to Milestones before adding tagging. And we need to seriously rethink the way we show tags in the drop down list. We can see our browser tag list can be hard to manage sometimes.

**Comment by miketaylr** [comment]
> Probably we would want to move the process stuff to Milestones before adding tagging.

Agreed.

**Comment by karlcow** [comment]
* "Discussion" for a label `type-cssRule` https://github.com/webcompat/web-bugs/issues/4856#issuecomment-283722562
* we created something for VR
* we are discussing of creating something for audio.

Cough cough. We are rushing ;) 
What about creating guidelines for creating and documenting the `type-` labels.

**Comment by miketaylr** [comment]
> Cough cough. We are rushing ;)

Are we? We had discussed this in our team meeting a few weeks back. The decision was to be liberal in our usage of `type-foo` labels for categorization of emergent issues. @adamopenweb volunteered to "clean them up" every month or so.

**Comment by miketaylr** [comment]
We're still waiting on Milestone stuff to happen and @magsout is starting some of the work that will unblock us from that now. I don't think we should not create new `type-foo` labels until that work is done.

**Comment by karlcow** [comment]
Just food for thoughts

Today I was looking briefly at the projects API
* https://developer.github.com/v3/projects/

I created 3 projects on 
https://github.com/karlcow/webcompat-test/projects

One issue can belong to more than one project (type-*)AND be part of ONE milestone (status-*).
https://github.com/karlcow/webcompat-test/issues/1

![capture d ecran 2017-03-23 a 13 38 17](https://cloud.githubusercontent.com/assets/505230/24232389/16c0b110-0fce-11e7-9c33-7759a0555010.png)

It's possible to create a project-card
https://developer.github.com/v3/projects/cards/#create-a-project-card

caveats: While it is possible to manually triage an issue and put it inside  a project column, I haven't an API way to do it.

**Comment by karlcow** [comment]
This is issue #997 
For the record I created things like type-css, etc.

**Comment by karlcow** [comment]
Let's close. it's an open ended questions. And we have since implemented multiple times: labels of different sorts since.
