### ISSUE TITLE
Simple bugform.js cleanup

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1199]
🚨 Wait until https://github.com/webcompat/webcompat.com/pull/1186 is merged, to avoid merge conflicts!

`BugForm.submitType` is unused (it was needed when we did a JS `FormData` POST to the relevant endpoint, but now we do regular form submission, so the server gets that from the multipart/form-data junk)

https://github.com/webcompat/webcompat.com/blob/f8c3b75122ee4ec6d918833b01f71c457a3bc9f5/webcompat/static/js/lib/bugform.js#L18

https://github.com/webcompat/webcompat.com/blob/f8c3b75122ee4ec6d918833b01f71c457a3bc9f5/webcompat/static/js/lib/bugform.js#L57

`loadingIndicator` and `loaderImage` can be consolidated into one (in usage as well):

https://github.com/webcompat/webcompat.com/blob/f8c3b75122ee4ec6d918833b01f71c457a3bc9f5/webcompat/static/js/lib/bugform.js#L12

https://github.com/webcompat/webcompat.com/blob/f8c3b75122ee4ec6d918833b01f71c457a3bc9f5/webcompat/static/js/lib/bugform.js#L14

**Comment by miketaylr** [comment]
> 🚨 Wait until #1186 is merged, to avoid merge conflicts!

Merged now.

**Comment by laghee** [comment]
I'd like to work on this to get started.  :-)

**Comment by miketaylr** [comment]
Great, @laghee! Let me know if you need any pointers.

**Comment by laghee** [comment]
Thanks, @miketaylr! So having pored over [this MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Submitting_forms_and_uploading_files), can I check my understanding with you? 

1. There's no need for a default value to be assigned to `this.submitType` on L18 since we can retrieve the value directly from the multipart/form-data as occurs on L57.
2. However, since `BugForm.submitType` isn't validated or otherwise used, then essentially L18 and the `function(e)` body on L57 can be eliminated -- leaving `this.submitButtons.on('click', _.bind()` parameters as `this.loadingIndicator.show()` and `this`.
3. Further, `loadingIndicator` && `loadingImage` can be merged into one attribute throughout (I'd pick "loadingIndicator" if that works?) since they get their value from the same segment of the form-data.

If I'm leaving anything out or misunderstood how something works, please let me know!

**Comment by miketaylr** [comment]
@laghee could you link to the line numbers? L18 and L57 from point 1 aren't matching up for me @ https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js. Thanks!

**Comment by miketaylr** [comment]
> Further, loadingIndicator && loadingImage can be merged into one attribute throughout (I'd pick "loadingIndicator" if that works?) since they get their value from the same segment of the form-data.

Yeah, they can be merged since they both refer to the same exact DOM element.

**Comment by miketaylr** [comment]
> There's no need for a default value to be assigned to this.submitType on L18 since we can retrieve the value directly from the multipart/form-data as occurs on L57.

Yep, we get that from the form data here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L192-L201

Which comes in from the button `name` that was clicked on:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/home-page/form.html#L103-L113

**Comment by miketaylr** [comment]
> However, since BugForm.submitType isn't validated or otherwise used, then essentially L18 and the function(e) body on L57 can be eliminated -- leaving this.submitButtons.on('click', _.bind() parameters as this.loadingIndicator.show() and this.

Yep! We just need to kick off showing the loading image (which is hidden in the XHR success handler: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L423

(I'm not sure why we're using `show()` and then just removing the `is-active` class in the success handler... but we call `hide()` in the error handler. 😕, possibly something to improve on).

**Comment by laghee** [comment]
Ahhh, OK -- I was missing the piece from: https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L192-L201

That all helps very much, thank you!

**Comment by laghee** [comment]
I see what you mean about `is-active` vs. `show()` and `hide()`. From what I understand, there's an advantage to adding/removing a class as opposed to calling `show()` or `hide()` in general because it allows for more style control over the item, but I'm not sure how important that is here.

Now that I look at the code again, I'm also puzzled about the difference between `js-Upload-Loader` and `js-Loader`. Are they for two different images? And if so, should the usage of `loaderImage` here: 

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L437

... be merged with `loadingIndicator` as discussed or changed to `uploadLoader`?

**Comment by laghee** [comment]
@miketaylr I can go ahead and send a PR if the changes are OK as is (stuck to the original discussion and didn't change anything related to `uploadLoader`), otherwise let me know if I need to go back and fix anything!

**Comment by miketaylr** [comment]
@laghee looks good! go ahead and send a PR, the one change I'd recommend is changing `this.loadingIndicator.show()` to just `this.loadingIndicator.show`.

**Comment by laghee** [comment]
@miketaylr Of course, I should have noticed that. OK, will do.
