### ISSUE TITLE
Add a referer header when new issues are created and redirected to issue page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1276]
See https://github.com/webcompat/webcompat.com/pull/1273#issuecomment-271752559

We can use that as a signal to show the "Thanks!" flash message, rather than the current (hacky, imo) solution of using `session`.

See https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L214 and all other instances of `session['show_thanks'] = True`

**Comment by nj4710** [comment]
Hi @miketaylr I would like to work on this

**Comment by miketaylr** [comment]
Cool! We might want to get @karlcow to review these patches when they're ready.

**Comment by karlcow** [comment]
I will remove the `status: good next bug` for now. As I think it requires a bit more knowledge. Let's rewind a bit and give a longer description of the issue. 


Some background.

An HTTP POST is not [idempotent](http://restcookbook.com/HTTP%20Methods/idempotency/) and not safe. It means that two subsequent `POST /issues/new` do not create the same results. In our case each of them will create a new issue and create a new URI. So when we do a POST the server is replying to us and provide a number. We want to use this number to redirect the browser to the URL of the issue and at the same time show a flash message.

In #1273, @miketaylr implemented a way to 
1. redirect the browser to the issue which has just been created aka through `POST /issues/new`.  
2. And show the Thanks message.

He is doing the Thanks message by storing in session a keyword with the value True.

```python
session['show_thanks'] = True
return redirect(url_for('show_issue', number=response.get('number')))
```

This is then used in `@app.route('/issues/<int:number>')` with `def show_issue(number):` where it is checked if `session` contains the right keyword to send the `show_thanks` and then removes it from the session. This function/route is used for showing issues. So we do not want to send the thanks message all the time. That's why there is the current session mechanism.

https://github.com/webcompat/webcompat.com/blob/5fdbb0dcfad3608f398517bd5ca5e8cbe0e3f5f1/webcompat/views.py#L208-L217

What I suggested in my comment is that instead of storing a session for this flash message. We just use the fact that we show the flask message only when we come from `POST /issues/new`. It means when accessing `/issues/<int:number>` we need to check the [HTTP `Referer`](https://tools.ietf.org/html/rfc7231#section-5.5.2) on the request. If it comes from `/issues/new` then we send a show thanks message. So instead of a `if session.get()…` we would use a `if request.referer`

Things to do:

* [ ] Create tests to make sure that the referer is here when we transition from `POST /issues/new` to `GET /issues/issue_number` Probably in[ test_urls.py](https://github.com/webcompat/webcompat.com/blob/5fdbb0dcfad3608f398517bd5ca5e8cbe0e3f5f1/tests/test_urls.py)
* [ ] Change the show_issue to use the referer
* [ ] Clean the code elsewhere that we are sure we don't use the two ways of doing things
* [ ] Make sure that we don't break the functional tests
* [ ] Run nosetests

**Comment by nj4710** [comment]
That was a great explanation. Thank you so much.
Sorry for my last commit. 
Can I at-least try and complete one of these tasks?
So, what I understand from this is we do not need to use `set_referer` or `get_referer` method in `def create_issue()`. We will need to remove the session variables from this function since we are not using them anymore.

Now, inside `show_issue(number)` we need to change the if condition, since we are checking the referer now. It will be `if request.referrer == ('/issues/new')` and then show the flask message.

Please correct me if I am wrong.
Also, am I eligible to work on this? Since my last PR is in review.
Thanks

**Comment by karlcow** [comment]
@nj4710 You are always welcome to work on things. And if you can't finish for any reasons it is ok too. And we will help along the way or find a solution together. 🆒

**Comment by nj4710** [comment]
I tried to complete the show_issue task. r? @karlcow

**Comment by miketaylr** [comment]
> I tried to complete the show_issue task. r? @karlcow

(Our process is to create a PR and ask for review in that, rather than a comment in a bug. :)) It's also OK to open up a PR and ask for feedback as you're developing things, before things are 100% ready for review.

**Comment by karlcow** [comment]
See my comments in @nj4710 Pull Request 
https://github.com/webcompat/webcompat.com/pull/1466#issuecomment-293447540

My initial idea was bad and that was discovered by exploring the pull request of @nj4710 
For the record, @nj4710 did a good work.

I'm closing the issue as wontfix. Thanks.
