### ISSUE TITLE
Add Contributor link to top navigation

### ISSUE THREAD

**Issue by lockettm** [webcompat/webcompat.com#1281]
Should we link to the Contributors page in the top nav? 

This could improve the onboarding flow of new volunteers as visitors may be overlooking the opportunity to contribute. Also, as a potential contributor, I’d expect to see a prominent community link once I landed on the page.

**Suggestion**
Prototype and user test a Contributor link in the top nav. 
![nav-contribute-2](https://cloud.githubusercontent.com/assets/4382193/21939242/b968bef8-d973-11e6-8839-fba39a69accb.jpg)

Possible link label: 
* Join
* Community
* Contribute

**Comment by miketaylr** [comment]
This is cool, @lockettm. Do you have a link to that icon? Hopefully it's open source because it's cool.

One thing to consider is the potentially awkward positioning at certain window widths:

<img width="787" alt="screen shot 2017-01-17 at 2 42 11 pm" src="https://cloud.githubusercontent.com/assets/67283/22039099/839f0662-dcc3-11e6-96e4-6729009a28a0.png">

We could address this in a few ways, possibly hiding the add-on link at a certain breakpoint where its problematic. But on mobile it seems good, and at desktop widths as well. Or maybe use ellipses on the addon link?

**Comment by lockettm** [comment]
Thanks @miketaylr. The icon is from the same set as the others in the top nav: http://fontawesome.io/icon/users/

I think hiding the add-on link for problematic widths is a good option. Otherwise, an add-on icon http://fontawesome.io/icon/puzzle-piece/ or the current download icon might work.

<img width="401" alt="screen shot" src="https://cloud.githubusercontent.com/assets/4382193/22042177/e5a4e9d0-dcbe-11e6-817e-951c5bbc218a.png">

**Comment by miketaylr** [comment]
Ah right, just showing the add-on icon seems better than hiding something entirely. 👍

**Comment by magsout** [comment]
oh yes, good idea.

`Contribute` is the best label IMHO 👍

**Comment by lockettm** [comment]
Updating this discussion to add a small note about the mockup user testing.

When tasked with finding an opportunity to work on, users most often selected the Contributor link at the top. Adding it seems like a good idea.

**Comment by zoepage** [comment]
Where should the icon link to?
https://webcompat.com/contributors could be a way to go, but also an anchor on the index that points to "join the team".

**Comment by zoepage** [comment]
In today's web compat meeting, we voted on the anchor on the index that points to `join the team`.

**Comment by zoepage** [comment]
Closing in favor of follow up issues #1404 and #1405
