### ISSUE TITLE
Back button missleading

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1287]
0. Start at the index page (https://webcompat.com/)
1. go to "report a bug"
2. hit the back button

-> I'll end up on the list of all bugs.

I understand why it is a good thing to push contributors to the list, so they can explore and help out. But this is confusing for new contributors, who are looking around.

-- edit --
I reproduced it before 6 times and now I can't. I'll leave it here so if it reappears, there is an issue already.

**Comment by karlcow** [comment]
Thanks a lot @zoepage for opening the issue. 

So with a fresh profile and a new window. (aka no history.) when I do the steps. The back button never changes its status, which is normal, because we don't change the navigation context.

On the other hand if in your history, a user go to the all bugs list, then to the home page, click on report a bug, then the back button it returns to the all bugs list (which is normal) :)

And yes if you can reproduce clearly and consistently that would be great.
