### ISSUE TITLE
[Issue] target="_blank" for link in issue detail

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1336]
Any thoughts?

**Comment by karlcow** [comment]
@magsout Could you be more descriptive, where, when why?

**Comment by magsout** [comment]
Where:

![capture d ecran 2017-02-09 a 09 47 53](https://cloud.githubusercontent.com/assets/1997108/22775636/e3b1e86c-eeac-11e6-8141-40f12c996244.png)


Added target blank on the URL in the main comment issue.


Why? Because to keep the tab open when we click on the URL to see/diagnosis/bug, especially on mobile

**Comment by karlcow** [comment]
hmm I'm not a big fan of things opening in new tab without user consent. Specifically when the feature exists already, aka long press (mobile) and ctrl/command+click or contextual menu (desktop). 

And it seems that normal people are usually confused 
http://ux.stackexchange.com/questions/19892/opening-website-external-links-in-new-window-published-usability-tests

**Comment by magsout** [comment]
>hmm I'm not a big fan of things opening in new tab without user consent. Specifically when the feature exists already, aka long press (mobile) and ctrl/command+click or contextual menu (desktop).

Me netiher, but webcompat is different than ecommerce or press website..  But yes feature already exists with the keyboard.

**Comment by zoepage** [comment]
@lockettm ? :)

**Comment by lockettm** [comment]
I think it’s a good idea. It would help reduce friction given the workflow of the task—the user won’t need to hit the back button or open the page using ctrl/command + click, they could simply select the link.

**Comment by zoepage** [comment]
To follow this up, decision is made on +1 the idea to add `target=_blank` for external links?

**Comment by miketaylr** [comment]
Let's go ahead and do it, and if people complain, we can re-consider. Personally, I use context-menu open in new tab.

**Comment by karlcow** [comment]
rha! sniff sniff 😢 

> if people complain

No I need to find a way to deactivate this in Firefox. Just to explain why I think it's a bad decision. We go from users having a choice to imposing to everyone opening in new windows. 

Also testing the site is (for me) never happening in the browser where I navigate webcompat.com.
See http://www.otsukare.info/2014/11/12/configure-webcompat-browser

Well… life.

**Comment by zoepage** [comment]
Okay, as @miketaylr said... let's do it?
(sorry @karlcow <3)

**Comment by magsout** [comment]
❤️  my @karlcow

**Comment by zoepage** [comment]
Decision was made. +1 on `'target="_blank" for link in issue detail`

**Comment by sergiorojasa** [comment]
I would like to work on this

**Comment by miketaylr** [comment]
There's a few ways this could be done, but perhaps the simplest way would be during clientside markdown processing here, similar to the way we add the `rel=nofollow` stuff:

https://github.com/webcompat/webcompat.com/blob/28ac4928f56dec681349fa977d619da3d2888eac/webcompat/static/js/lib/issues.js#L59

(That way, if we decide to turn this feature off, we don't have to worry about hard-coded `target` attributes in the GitHub issue body.)

**Comment by karlcow** [comment]
@miketaylr the nofollow is implemented on **all links**. 

Please, let's implement **this only** on the URL link in the description. Not in the comments. That would turn into a "nightmare".

**Comment by miketaylr** [comment]
Ah yeah, OK whoops. Then we should do this at the backend level.

**Comment by moraveyo** [comment]
Can I work on this (my first bug)?

**Comment by magsout** [comment]
@moraveyo enjoy 👍

**Comment by moraveyo** [comment]
I'm new to this project, need some guidance please

**Comment by karlcow** [comment]
@moraveyo this probably requires a bit of python knowledge if on the server side.
JS if done on the client side.

ok let's see. 
Assuming that as you said on IRC, that you successfully a `python run.py` on the project.
And that you can see some issues like `http://localhost:5000/issues/100`.

so you should see something like

![capture d ecran 2017-03-29 a 17 17 37](https://cloud.githubusercontent.com/assets/505230/24445067/aaf7aac6-14a3-11e7-87ff-67ac2c11ae23.png)

The proposal on this issue is to have the URL: link open in a new tab/window.

Currently the markup is 

```
<div class="js-Issue-markdown wc-Markdown">
    <p><strong>URL</strong>: <a href="http://www.mmmmm.com" rel="nofollow">www.mmmmm.com</a>
        <br>
        <strong>Browser</strong>: Firefox
        <br>
        <strong>Version</strong>: 30</p>
    <p>The site asks me to upgrade</p>
</div>
```

and some users want to have 

```html
    <p><strong>URL</strong>: <a href="http://www.mmmmm.com" rel="nofollow">www.mmmmm.com</a>
```

We currently use a markdown renderer for converting the  text only into `html`. What needs to be done is something that will add a `target="_blank"` **only on this link**. It's probably why @miketaylr said on the server side. 

The current view is generated by `@app.route('/issues/<int:number>')`
https://github.com/webcompat/webcompat.com/blob/3cf04f4eda26f920d2aa97ff54ad729e43ae5d29/webcompat/views.py#L208-L217

which calls 
https://github.com/webcompat/webcompat.com/blob/3cf04f4eda26f920d2aa97ff54ad729e43ae5d29/webcompat/templates/issue.html

which is basically a dumb (empty semantics) HTML file, which is populated after the request by a JavaScript.

The JS is doing a request to https://github.com/webcompat/webcompat.com/blob/3cf04f4eda26f920d2aa97ff54ad729e43ae5d29/webcompat/api/endpoints.py#L35-L43

which itself is doing a request to github. 
https://github.com/webcompat/webcompat.com/blob/3cf04f4eda26f920d2aa97ff54ad729e43ae5d29/webcompat/helpers.py#L441-L462

During all these dance we receive a JSON file from Github containing the text that will be htmlized. So we could imagine that before passing it to the template we at least convert the URL link into HTML with a target blank. That should not impact the Markdown renderer, because you can mix markdown and html in markdown.

Does it help a bit. You can ask more specific questions. There's probably more than one way to do it. And it requires a bit of thinking for doing it right, but no worries because we are here to discuss and review any choices you would make and eventually find a solution which works for everyone.

**Comment by karlcow** [comment]
I'm removing good first bug, because there's quite a bit of work to achieve this.

**Comment by miketaylr** [comment]
I'm gonna steal this one. And do it only with JS.
