### ISSUE TITLE
Contributors guideline section remains highlighted when tapped/clicked on Chrome browser

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1488]
Browser / Version: Chrome 56.0.2924, Chrome 57.0.2987
Operating System: Windows 10 Pro,  Android 6.0.1

**Steps to Reproduce**
1.	Navigate to: https://webcompat.com/contributors.
2.	Click/Tap a guideline section.
3.	Observe behavior.

**Expected Behavior:**
Section is not highlighted.

**Actual Behavior:**
Section remains highlighted.

**Notes:**
1.	Not reproducible on Firefox Nightly 55.0a1 and Release 52.0.2.
2.	Screenshot attached.

sv; 

![guidelinesectionhighlight](https://cloud.githubusercontent.com/assets/12184325/24743214/20a735f8-1ab6-11e7-92fe-08dc7e661d23.png)

**Comment by magsout** [comment]
Thanks @softvision-oana-arbuzov. It's beacuse of outline on a button in (webkit/blink).

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/contributors.css#L31

Just add this property 

```css
.contributors__item__btn {
  outline: none;
}

But outline is for accessibility, so we need to provide something more to replace this behavior.

What do you think @zoepage  ?

**Comment by miketaylr** [comment]
I think this page will eventually be redesigned, so I would consider this lower priority than others.

**Comment by zoepage** [comment]
Shall we close this one as this page will be redesigned and the "highlighting" behavior unified?

**Comment by zoepage** [comment]
To clarify, we need to add a "highlighting" behavior for links to keep the site accessible. 
Maybe @aminalhazwani or @stefanjudis have an idea how to solve this best?

**Comment by stefanjudis** [comment]
The [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion) have clear guidelines on how an accessible accordion should behave and also offer [an example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) (it's not pretty though ;) ). Heydon Pickering wrote [a massive article](https://inclusive-components.design/collapsible-sections/) on how to build accordions best, too.

Regarding the focus outline, removing it is not a good idea because it makes it unusable for keyborad navigation. `outline: none` would "fix" the outline on click, but also remove it when a user 'tabs'  around.

With a few design tweaks, focus state could be prettier though. Which in my opinion is usually good enough. :)

Another option would be to bet on the fairly new `focus-ring` pseudo-class which makes it possible to get rid of the outline on click but keep it on keyboard navigations. That's really cool stuff.

**Disclaimer:** it's not that well supported yet so there would be two options:

- just use `focus-ring` and Firefox (only [one supporting right now](http://caniuse.com/#feat=css-focus-ring)) won't show the outline on click all other vendors do show it -> this might feel like a compat bug but I'd see it more as progressive enhancement similar to the old days with `border-radius` (if browsers didn't understand borders, they didn't show it - which was fine)
- bring in [a polyfill](https://github.com/WICG/focus-ring). 

Hope this helps. :)

**Comment by zoepage** [comment]
Thanks @stefanjudis for your answer. It helps a lot :)

> With a few design tweaks, focus state could be prettier though. 

What would you suggest for design tweaks? Any ideas?

> Another option would be to bet on the fairly new focus-ring pseudo-class which makes it possible to get rid of the outline on click but keep it on keyboard navigations.

I really like this idea! Even with using the polyfill. What do the others think about it?

**Comment by stefanjudis** [comment]
> What would you suggest for design tweaks? Any ideas?

I don't know... just quickly tried to "design" something. :D To me this looks already way better than outline. :)

![compat-focus](https://user-images.githubusercontent.com/962099/32399727-bfa9ee32-c0f8-11e7-95f1-f4495b938a6e.gif)

**Comment by zoepage** [comment]
Closing in favor of https://github.com/webcompat/webcompat.com/issues/1917 and the new sub navigation.
