### ISSUE TITLE
Functional tests fail starting with a certain test

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1569]
The tests fail on all branches. It would appear that the tests fail from: `Going back in history updates issue list and URL state`

```
× firefox on any platform - Issue-list - Going back in history updates issue list and URL state
```

Fx ANY:     [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓×××××✓✓✓✓×××✓\      ] 65/78, 15 fail

**Comment by zoepage** [comment]
@miketaylr @brizental 
Would one of you be able to take a look here? Thanks!

**Comment by miketaylr** [comment]
I don't think this reproduces for me. @brizental does it for you?

**Comment by brizental** [comment]
I just changed from Ubuntu to MacOS an this has started happening to me too... I'll have a look, now that I can reproduce it.

**Comment by miketaylr** [comment]
whoops, this reproduces for me now (using v54 stable):

<img width="751" alt="screen shot 2017-06-15 at 4 24 59 pm" src="https://user-images.githubusercontent.com/67283/27185989-56128090-51e7-11e7-9c8b-915e702b7f93.png">

**Comment by miketaylr** [comment]
Failing test starts here: https://github.com/webcompat/webcompat.com/blob/master/tests/functional/issue-list-non-auth.js#L290

**Comment by brizental** [comment]
The problem is that the `goBack()` function (https://github.com/webcompat/webcompat.com/blob/master/tests/functional/issue-list-non-auth.js#L320) should return a Promise but it never returns anything.

I tried to look and see if the problem is in our code, but I didn't find anything wrong, so I think that this might be a problem in Leadfoot, it only happens for the newest Firefox versions, like 54 and forward. I  also tried to mess around with Leadfoot's code, but didn't have success.

Apparently everything is working fine, the URL changes right as it should and everything, it just gets stuck in some Promise limbo and never gets to the next line (https://github.com/webcompat/webcompat.com/blob/master/tests/functional/issue-list-non-auth.js#L321). Also if you manually refresh the page when it gets stuck it gets going again.

I'll keep on investigating, but just wanted to see if anybody has any ideia of what might be happening :)

**Comment by miketaylr** [comment]
> so I think that this might be a problem in Leadfoot, it only happens for the newest Firefox versions, like 54 and forward.

It's also possible it's a Geckodriver bug or regression: https://github.com/mozilla/geckodriver
