### ISSUE TITLE
"Issue comments load" test results inconsistent across travis and local tests

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1584]
the assertion for this test passes on travis but fails when run locally

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/issues-non-auth.js#L61

if the date is changed to pass locally (using the date, Thu Oct 01 2015), it would fail on travis. I don't know how to fix this but in the least case it could be documented for developers (expected to fail locally).

**Comment by karlcow** [comment]
Yes there are a couple of issues with this test. but it is surprising it is failing locally, or more exactly the tests are relying on the user having configured https://github.com/webcompat/webcompat-tests/ for the tests repository. If indeed we configure another repo, we will get an error. Strong dependency. 

```js
          .findByCssSelector(".js-Comment-content")
          .getVisibleText()
          .then(function(text) {
            assert.equal(
              text,
              "Today's date is Mon Sep 28 2015",
              "Comment is displayed."
            );
```

If I execute `.js-Comment-content` on inspecting `http://localhost:5000/issues/100`, it finds the first comment on a series of currently 20.


```html
<div id="issuecomment-144794620" class="wc-Comment js-Issue-comment">
  <div class="wc-Comment-body">
    <div class="wc-Comment-wrapper">
      <div class="wc-Comment-header">
        <div class="wc-Comment-owner">
          <div class="wc-Comment-owner-avatar">
            <img src="https://avatars2.githubusercontent.com/u/7131070?v=3" alt="GIGANTOR">
          </div>
          <div class="wc-Comment-owner-name js-Comment-owner">
            <a class="wc-Link" href="https://github.com/GIGANTOR">GIGANTOR</a>
          </div>
        </div>
        <div>
          <a class="wc-Link" href="#issuecomment-144794620">2015-10-02</a>
        </div>
      </div>
      <div class="wc-Comment-content js-Comment-content">
        <div class="wc-Markdown">
          <p>Today's date is Thu Oct 01 2015</p>

        </div>
      </div>
    </div>
  </div>
</div>

```

which relates to this comment.
https://github.com/webcompat/webcompat-tests/issues/100#issuecomment-144794620

1. The selector should probably be more specific in a way we currently do the tests, because anyway we rely on being `https://github.com/webcompat/webcompat-tests/`. So we could target with `#issuecomment-144794620`. We could also emit a warning when starting the tests that if not `https://github.com/webcompat/webcompat-tests/` the tests will fail. 
2. If we end up being successful with mocking GitHub responses, then we could send controlled data and not being dependent on GitHub, hence the specific repo for testing.

**Comment by cch5ng** [comment]
@karlcow thanks. in the docs, it seemed like it was expected to create a unique test repo but I will update my settings then.

https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#configuring-the-server

**Comment by cch5ng** [comment]
@karlcow I think my secrets.py file is missing some setup to use the webcompat-bot user for running tests. right now if I create an issue from localhost:5000, the issue does get created here:

https://github.com/webcompat/webcompat-tests/issues (but always with my regular login and when I run functional issues tests, still getting the original issue noted above)

should I assume I probably need to update the secrets.py OAUTH_TOKEN value?

**Comment by miketaylr** [comment]
> @karlcow I think my secrets.py file is missing some setup to use the webcompat-bot user for running tests. right now if I create an issue from localhost:5000, the issue does get created here:

@cch5ng I can share the secrets with you here in SF. :)

**Comment by cch5ng** [comment]
closing as the issue was fixed by running tests using fixtures

`python run.py -t`
