### ISSUE TITLE
The Report Anonymously button should have gray border 

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1650]
Browser / Version: Chrome 59.0.3071.115 (Desktop), Firefox 54.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/new
2. Observe the border colour of the Report Anonymously and Report as [GitHub user].

**Expected Behavior:**
The Report Anonymously button should have gray border.

**Actual Behavior:**
The Report Anonymously button has yellow border.

**Notes:**
1. The current border colours are not consistent with the previous version of webcompat.com.
2. Screenshot attached.
![croppedscreenshotarea_2xtab](https://user-images.githubusercontent.com/16573771/28016923-3c98d47e-657f-11e7-9dd7-286dceb37ce2.png)

sv;

**Comment by Akshitaag** [comment]
Hii.
Can i work on this? I am a beginner.How do i proceed?

**Comment by denschub** [comment]
Hi @Akshitaag! You sure can work on this! It's good to start with reading our [`CONTRIBUTING.md`](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md), which describes the entire process from getting the sources to your machine to finally submitting a pull request in fair detail.

If you run into any issue, we do have an [IRC channel](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#questions-or-problems) you can join and ask for help. Please note that if you try to get help on IRC, asking on workdays usually works way better since people tend to not work on weekends. :) However, timezones should not matter too much since our team is spread evenly across the world.

**Comment by Akshitaag** [comment]
@denschub thank you for your response
i am running into an error while trying to build up a development environment on cloud9. Should i ask in irc ?

**Comment by zoepage** [comment]
@Akshitaag You can ask your question here and if you need a more urgent answer, IRC would work too. :)

**Comment by Akshitaag** [comment]
when i run 'npm run setup ' below stated error occurs:

npm run setup

> webcompat@ setup /home/ubuntu/workspace
> npm run module && npm run virtualenv && npm install && npm run config


> webcompat@ module /home/ubuntu/workspace
> git submodule init && git submodule update


> webcompat@ virtualenv /home/ubuntu/workspace
> pip install virtualenv && virtualenv env && source env/bin/activate || . env/bin/activate && npm run pip

Downloading/unpacking virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB): 1.8MB downloaded
Installing collected packages: virtualenv
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/virtualenv-15.1.0.dist-info'

Storing debug log for failure in /home/ubuntu/.pip/pip.log
sh: 1: .: Can't open env/bin/activate

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "virtualenv"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! webcompat@ virtualenv: `pip install virtualenv && virtualenv env && source env/bin/activate || . env/bin/activate && npm run pip`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the webcompat@ virtualenv script 'pip install virtualenv && virtualenv env && source env/bin/activate || . env/bin/activate && npm run pip'.
npm ERR! This is most likely a problem with the webcompat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pip install virtualenv && virtualenv env && source env/bin/activate || . env/bin/activate && npm run pip
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcompat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webcompat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.7.3/bin/npm" "run" "setup"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! webcompat@ setup: `npm run module && npm run virtualenv && npm install && npm run config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcompat@ setup script 'npm run module && npm run virtualenv && npm install && npm run config'.
npm ERR! This is most likely a problem with the webcompat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run module && npm run virtualenv && npm install && npm run config
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcompat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webcompat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by zoepage** [comment]
@Akshitaag looks like you need to grand permission, so the install can run through. 
```
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/virtualenv-15.1.0.dist-info'
```
Did you try `sudo pip install virtualenv`?

**Comment by Akshitaag** [comment]
@zoepage thanks for your help.It worked

**Comment by Akshitaag** [comment]
Configuration Problem:
Under configuring the server:
How do i proceed with the step 3:
Step 3:Add the client id and client secret to secrets.py. If you're part of the webcompat GitHub organization, you can get the client id and client secret from GitHub. Otherwise, create your own test and production applications (instructions here) — when prompted for a "Authorization callback URL", use http://localhost:5000/callback,(Cloud 9 users should use http://yourapp.c9users.io:8000/callbackinstead) and take note of the client id and client secret GitHub gives you.

**Comment by miketaylr** [comment]
> How do i proceed with the step 3:

Did you follow the create the app at https://github.com/settings/applications/new? (Be sure to write down the id and secret, and put that in secrets.py around here: https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example#L62)

**Comment by miketaylr** [comment]
Also, that's probably not 100% necessary unless you plan on testing issue creation -- the app should boot up without that (meaning it should work unless you try to create a new issue.

**Comment by rheaparekh** [comment]
Hello, I am new here. Can I continue with this issue?

**Comment by apoorvasingh17** [comment]
I'm a beginner and would like to work on this issue. Can anyone give me some pointers regarding the same?

**Comment by denschub** [comment]
Basically yeah, everyone is welcome to contribute. We have a nice documentation in [`CONTRIBUTING.md`](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md) which covers everything from picking an issue to creating a pull request. Also, if you are stuck somewhere, the document also includes information on how and where to get help!

@apoorvasingh17 I've noticed you commented on multiple issues! While I (and certainly everyone else in the team) highly appreciates your enthusiasm, it is probably better to only pick one issue at a time. Feel free to pick the issue you'd like to work on and leave a comment that you are indeed working on that, but in general, we'd like to avoid having one person "reserving" issues, so that others have a chance to jump in as well. :)

**Comment by apoorvasingh17** [comment]
@denschub Thank you for the helpful suggestion. Will keep it in mind :)
