### ISSUE TITLE
"How did you get there?" text area should display an error if no info was typed

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1659]
URL: www.webcompat.com  
Browser / Version: Firefox 54.0.1, Chrome 59.0.3071.115.
Operating System: Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Type in the URL, set the “Type of bug” and type in the “Please describe what was wrong” field. 
4. Remove all info from “How did you get there?” text area.
5. Observe “Report” button behavior.

**Expected Behavior:**
Error message is displayed (“Steps to reproduce required”) and “Report” button becomes active after typing some info in the text area.

**Actual Behavior:**
No error message is displayed and “Report” buttons are active.

**Notes:**
1. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![noinfotextarea](https://user-images.githubusercontent.com/12184325/28202699-4090f568-687f-11e7-8056-0823534f0aaf.png)
![errorsugestion](https://user-images.githubusercontent.com/12184325/28202705-44939760-687f-11e7-8228-aa6020d8c522.png)

**Comment by zoepage** [comment]
The area is optional right now. We had a very long discussion at the Berlin work week about this. 
Sometimes people report bugs e.g. on their phone and don't have a lot of time to add more info. As the info is extremely helpful, I understand that issue, but we decided on having a bug report is more important than having none at all, because it was too much hassle for someone to add info.
