### ISSUE TITLE
bad file path in .travis.yml file causes travis process to exit early

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1673]
the travis build/test process is exiting early

error: The command "pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example" failed and exited with 1 during .

looks like unnecessary spaces somehow got inserted in the path:
https://github.com/webcompat/webcompat.com/blob/master/.travis.yml#L46

**Comment by miketaylr** [comment]
> error: The command "pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example" failed and exited with 1 during .

That means you have a linting error somewhere, rather than a problem with that specific line.

(https://github.com/webcompat/webcompat.com/commit/1ea1a7d786ab035eba8430d50988482f93244c90 hasn't changed since Dec 2015, so if it's failing now it's a hint that your code is violating some pep8 linting rule).

**Comment by miketaylr** [comment]
@cch5ng https://travis-ci.org/webcompat/webcompat.com/builds/256998399#L603 has the error pep8 was complaining about:

`webcompat/form.py:62:1: E302 expected 2 blank lines, found 1`

Let's go ahead and close this issue.

**Comment by cch5ng** [comment]
ah, sorry about that. the error was confusing but will add a note to
include pep8 in my checklist.
