### ISSUE TITLE
Network dependency for test_api_urls.py with milestone

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1793]
When developing the tests for milestones API endpoint, I introduced again a dependency over the network.

https://github.com/webcompat/webcompat.com/blob/7f7d17750f356515659e7e47e94ac95025d85ce8/tests/test_api_urls.py#L171-L176

**Comment by brizental** [comment]
If you prefer I can work on this @karlcow :)

**Comment by karlcow** [comment]
With pleasure @brizental 👍

**Comment by brizental** [comment]
So, I've got an issue here. I tried patching this exactly like I did the other ones, but since you call the `proxy_request` function from inside the `endpoints.py` file, you have to it differently.

From the [documentation](http://www.voidspace.org.uk/python/mock/patch.html#id1):
> patch works by (temporarily) changing the object that a name points to with another one. There can be many names pointing to any individual object, so for patching to work you must ensure that you patch the name used by the system under test.

Following this train of thought, the target for the patch function would be `webcompat.api.endpoints.proxy_request`, but that doesn't work, because `webcompat.api` points to the a Blueprint object (https://github.com/webcompat/webcompat.com/blob/master/webcompat/__init__.py#L31).

Now, I found a solution for this: if you change the name of the api folder to something else, it works, because it doesn't get overruled by the Blueprint.

Anyways, I thought it would be best to see if you know any other solution @karlcow , before going with it. And even if changing the name of the folder is the only solution, I think maybe it should be discussed first, hehe.

**Comment by karlcow** [comment]
@brizental Does it change anything if you use relative imports, aka with a "."

**Comment by karlcow** [comment]
another idea inside the app_context

```
from api.endpoints import api
app.register_blueprint(api)
```

then mocking.

**Comment by brizental** [comment]
With the app context now it works :)

**Comment by brizental** [comment]
Sorry for the duplicate commits, I had a little confusion because milestones is the 'parent' branch not the master. Anyways, using the patch inside app_context() alone worked already :)

**Comment by karlcow** [comment]
Closed by #1825
