### ISSUE TITLE
Enter in description textbox submits form

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1794]
As described in this bug: https://github.com/webcompat/web-bugs/issues/9706

If you press enter in the description textbox, it submits the form before you've (potentially) finished filling it out.

Maybe we should prevent this behaviour and force the user to click the button?

**Comment by miketaylr** [comment]
Yeah, that's crappy behavior, IMO.

**Comment by softvision-sergiulogigan** [comment]
I just made the "Enter" mistake on https://github.com/webcompat/web-bugs/issues/14683
I too think that submitting an issue should be done exclusively by clicking the Report button (or Tabbing your way there and hitting the Spacebar)

Curious enough, the issue got submitted as Anonymus, despite the fact I was logged in.

**Comment by miketaylr** [comment]
> Curious enough, the issue got submitted as Anonymus, despite the fact I was logged in.

Ah, I know why. We rely on which button you've clicked (to allow logged in users to report things anonymously if they prefer). The current bug is sort of undefined behavior...

**Comment by softvision-sergiulogigan** [comment]
Let's put this https://github.com/webcompat/web-bugs/issues/16299 for refference.

**Comment by Regaddi** [comment]
Description is not a multiline field at all, it's just a normal single line input field.
Hitting enter there for sure triggers a submit (which applies to every single line input field in that form, like URL, browser and operating system).

However it only triggers the form submit, when all required fields contain technically valid information.

We could prevent the submit by hitting keyboard enter generally, which is from an accessibility point of view not ideal. Also it would require some extended event handling for keyboard events on the form in a whole.

So there are multiple possible approaches to tackle this issue:

1. Prevent `enter` events and force the users to click one of the submit buttons
2. Before submitting the form with `enter`, let the user confirm the action by using a confirm dialog (in the simplest form this might be a `window.confirm()`. An extended version might take usage of some HTML modal dialog with a "preview" of the issue details.
3. Do nothing, since `enter` is a completely valid way to submit web forms.
4. Instead of submitting the form using `enter` we could tab to the next field, which is probably not, what a user expects to happen when he hits `enter`.

What do you think? @zoepage @miketaylr

**Comment by miketaylr** [comment]
I think #1 is the least surprising.

**Comment by zoepage** [comment]
+1 on 1. :)
