### ISSUE TITLE
Better error messaging for unset milestones

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1856]
Followup on #1852 
Two scenarios, the messages should be along:

* **Anonymous**:  "No assigned status yet" as they can't do anything about it and error will lead to error report. No red color.
* **Logged in**: "Fix me: assign a status"

@zoepage  @miketaylr What do you think about it?

<img width="694" alt="capture d ecran 2017-11-01 a 09 47 57" src="https://user-images.githubusercontent.com/505230/32255230-d1eb4dae-bee9-11e7-8875-4fafeffcc066.png">

Once modified. (through developer tools for the mockup)

<img width="689" alt="capture d ecran 2017-11-01 a 09 50 30" src="https://user-images.githubusercontent.com/505230/32255289-22baba9e-beea-11e7-872f-d19ee0d6429a.png">

**Comment by miketaylr** [comment]
Yeah, I think this is a much better solution @karlcow. +1

**Comment by marimeireles** [comment]
I'm getting this one!
Thanks Karl.

**Comment by marimeireles** [comment]
Hi people, sorry for taking so long to solve this issue. I don't have a lot of free time because I'm still on my school semester and I was concentrating on the mini project. I'll try to fix this today!

**Comment by magsout** [comment]
@ marimeireles  no worries, thanks for your help

**Comment by marimeireles** [comment]
@magsout 
Do you think it's a better idea to create a broader css class called logged-out and put the changes there or is it better to create a specific class that only changes what the issue is referring to?

I could do like this: class="{{'logged-in' if session.username else 'logged-out'}}"` 
or should I just: class="{{'issue-labels-logged-in' if session.username}}"` ?

Also, do you think these class names make sense?

**Comment by magsout** [comment]
@marimeireles state class are good idea. But I think prefix with `is`  is better IMHO, like `is-logeed-in`

>I could do like this: class="{{'logged-in' if session.username else 'logged-out'}}"

👍
