### ISSUE TITLE
Remove css-fixme

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1862]
As CSS FixMe seems not fully maintained, the idea came up to remote it from the repository and I second that idea. 
There is also always the option to deploy it separately. 

What do you think @adamopenweb @wisniewskit @MDTsai @denschub @miketaylr @karlcow?

**Comment by karlcow** [comment]
@zoepage 

> the idea came up to remote it from the repository

I don't understand that sentence. 
CSS fixme is not really in webcompat.com currently.

It is (un)maintained at
https://github.com/webcompat/css-fixme

The URIs, templates, etc are, see below:

See below.
```
.gitignore
26:webcompat/static/js/cssfixme.js

CHANGELOG.md
476:* Tweak highlight color for cssfixme [Pull #927](https://github.com/webcompat/webcompat.com/pull/927) [Issue #926](https://github.com/webcompat/webcompat.com/issues/926)
500:* Various improvments around cssfixme tool layout and style [Pull #891](https://github.com/webcompat/webcompat.com/pull/891) [Pull #887](https://github.com/webcompat/webcompat.com/pull/887) [Issue #848](https://github.com/webcompat/webcompat.com/issues/848)
506:* Fix cssfixme scripts in wrong location [Pull #876](https://github.com/webcompat/webcompat.com/pull/876) [Issue #875](https://github.com/webcompat/webcompat.com/issues/875)
512:* Handle ?url query string for cssfixme [Pull #852](https://github.com/webcompat/webcompat.com/pull/852) [Issue #847](https://github.com/webcompat/webcompat.com/issues/847)
513:* Add route and minimal style for cssfixme [Pull #849](https://github.com/webcompat/webcompat.com/pull/849) [Issue #12](https://github.com/webcompat/webcompat.com/issues/12)

grunt-tasks/concat.js
70:    cssFixmeLibs: {
76:      dest: "<%= jsPath %>/cssfixme.js"

grunt-tasks/uglify.js
35:    cssFixmeLibs: {
36:      src: "<%= concat.cssFixmeLibs.dest %>",
37:      dest: "<%= jsPath %>/cssfixme.min.js"

tests/test_rendering.py
50:            ('/tools/cssfixme', 'CSS Fix Me'),

tests/test_urls.py
98:    def test_tools_cssfixme(self):
99:        """Test that the /tools/cssfixme route gets 200."""
100:        rv = self.app.get('/tools/cssfixme')
108:    def test_tools_cssfixme_with_URL(self):
109:        """Test that the /tools/cssfixme route gets 200 with ?url query."""
110:        url = '/tools/cssfixme?url=https://webcompat.com/css/webcompat.min.css'
114:    def test_tools_cssfixme_with_nonsense_URL(self):
115:        """Test that the /tools/cssfixme route gets 200 with bad ?url query."""
116:        rv = self.app.get('/tools/cssfixme?url=foobar')

webcompat/static/css/development/components/cssfixme.css
6:  --CSSFixme-fontSize: var(--base-fontSize);
7:  --CSSFixme-backgroundColor: rgba(249, 249, 249, .6);
8:  --CSSFixme-backgroundColorStrong: var(--base-colorDark);
9:  --CSSFixme-preBorderColor: var(--base-colorDark);
12:.wc-CSSFixme {
13:  font-size: var(--CSSFixme-fontSize);
17:.wc-CSSFixme-item {
22:.wc-CSSFixme-instruction {
28:.wc-CSSFixme-resultat,
29:.wc-CSSFixme pre { /* stylelint-disable selector-no-type  */
34:  border-color: #ddd #ddd #ddd var(--CSSFixme-preBorderColor);
37:  background: var(--CSSFixme-backgroundColor);
41:.wc-CSSFixme-resultat strong {
42:  background-color: var(--CSSFixme-backgroundColorStrong);

webcompat/static/css/development/main.css
46:@import "components/cssfixme";

webcompat/static/js/lib/css-fixme-ui.js
4:  pre.className = "wc-CSSFixme-resultat";
5:  var preParentID = "js-CSSFixme";
6:  var cssfixmeInit = false;
11:      if (cssfixmeInit) {
47:      cssfixmeInit = true;

webcompat/templates/cssfixme.html
7:      <div class="wc-CSSFixme">
9:        <div class="wc-CSSFixme-instruction">
10:          <div class="wc-CSSFixme-item">
13:          <div class="wc-CSSFixme-item">
16:          <div class="wc-CSSFixme-item">
20:        <div class="wc-CSSFixme-item">
23:        <div class="wc-CSSFixme-item">
28:        <div class="wc-CSSFixme-item">
31:        <div class="wc-CSSFixme-item">
32:          <div id="js-CSSFixme"></div>
34:        <div class="wc-CSSFixme-item">
46:<script src="{{ url_for('static', filename='js/cssfixme.min.js')|bust_cache }}"></script>
48:<script src="{{ url_for('static', filename='js/cssfixme.js') }}"></script>

webcompat/views.py
338:@app.route('/tools/cssfixme')
339:def cssfixme():
341:    return render_template('cssfixme.html')
```

Now the question is what are you trying to solve? :)

If it's a question of design, it doesn't have to follow the site redesign. For me the site redesign is orthogonal to the subprojects. Aka all pages under webcompat.com don't have to look the same AND it's quite easy to manage a separation of concerns in Flask. 

For the history :) the project was initially developed by hallvord, and hosted on his own domain name. Then we moved it under the domain name webcompat.com removing some features because of security issues.

@adamopenweb do people still use it? (Access stats) Not sure we even track those.
@miketaylr suggested in the past to retire it. It's a possibility. We can do that properly here. 

https://github.com/webcompat/webcompat.com/blob/c1aa8356d4575c8b5fb956c0ae59942196d49088/webcompat/views.py#L331-L334

So summary of my position:

* If we think, it's not useful anymore, let's retire it with a nice message explaining the reasoning and its repo location.
* If it's because of design, then no, it doesn't seem a good reason as we can separate these easily. Example of organizational models http://exploreflask.com/en/latest/blueprints.html#where-do-you-put-them All Web pages don't have to look the same (fabric of time, rusty Web and its Aesthetics, etc. insert here a long story on [one of my favorite musings about the Web](https://vimeo.com/83618670).)

**Comment by zoepage** [comment]
@karlcow 
It's a submodule right now and a dependency we support.

It would take away a dependency plus 2 steps on a fresh install and yes, we would remove also the routes.

Plus when it's deployed, I feel like we should at least maintain it and we don't. :)

**Comment by karlcow** [comment]
I don't mind retiring it. :) See above.

> yes, we would remove also the routes.

nope :) We would change the route to a [410 Gone](https://tools.ietf.org/html/rfc7231#section-6.5.9) like we [did for rate-limits](https://github.com/webcompat/webcompat.com/blob/c1aa8356d4575c8b5fb956c0ae59942196d49088/webcompat/views.py#L269-L283). We should probably be more explicit about the 410 Gone and explain where the code lives if people want to host it elsewhere, but these are details to iron.

**Comment by denschub** [comment]
It's only JS and static HTML, right? I see no harm in using Github Pages to serve the contents on `http://webcompat.github.io/cssfixme/` or something. We could easily forward the requests from webcompat.com, thus reducing the maintenance need in this repo, while keeping the tool up and running in case someone wants to use it.

Setting that up wouldn't take much time, and the tool would still be up in case someone gets motivated to work on that. Also, hosting via GitHub pages would make deploying sooo much easier!

**Comment by miketaylr** [comment]
I think it's only theoretically useful at this point, since all evergreen browsers support `-webkit-` prefixes. I'm not sue it's even worth re-hosting. 

My vote would be 410 Gone w/ message to repo link. But if someone wants to adopt it, and actively maintain it, that's cool too. 
Right now, it's unmaintained https://github.com/webcompat/css-fixme/issues

**Comment by zoepage** [comment]
I feel the same way as @miketaylr. If anyone wants to adopt this project and take care if it... Cool. 

Otherwise +1 on 410.
