### ISSUE TITLE
Complete the webhooks tests coverage

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1955]
The webhook handlers run in our app, and they just react to JSON coming from GitHub, so we should be able to test them (which would prevent us from breaking them in the future :cough: sorry :cough:).

**Comment by karlcow** [comment]
(I'm changing the title ;) )

Note that we are already testing most of it, through dedicated helpers functions. 
What happened in #1952 is a undetected failure of `new_opened_issue`

https://github.com/webcompat/webcompat.com/blob/5b6cdd9c0bf8cde7f9a35095f081c8a41d6aa37b/webcompat/webhooks/helpers.py#L152-L171

And indeed… there is 0 test for new_opened_issue in 
https://github.com/webcompat/webcompat.com/blob/5b6cdd9c0bf8cde7f9a35095f081c8a41d6aa37b/tests/test_webhook.py#L38

Let's fix that and try to reproduce the issue, we had the last couple of days.

**Comment by karlcow** [comment]
Taking notes… about this to have a better understanding on what we 

`new_opened_issue` in https://github.com/webcompat/webcompat.com/blob/5b6cdd9c0bf8cde7f9a35095f081c8a41d6aa37b/webcompat/webhooks/helpers.py#L152-L171

calls `update_issue` in https://github.com/webcompat/webcompat.com/blob/5b6cdd9c0bf8cde7f9a35095f081c8a41d6aa37b/webcompat/webhooks/helpers.py#L79-L94

which in return calls `proxy_request` in https://github.com/webcompat/webcompat.com/blob/5b6cdd9c0bf8cde7f9a35095f081c8a41d6aa37b/webcompat/helpers.py#L438-L457

Then the next call in the chain is from a library. So let's ignore it for now.

```python
    update_response = update_issue(
        {'labels': labels, 'milestone': milestone}, issue_number)
    # return update_issue({'labels': labels, 'milestone': milestone},
    #                     issue_number)
    print(update_response)
    print(dir(update_response))
    return update_response
```

to test this locally on the CLI and makes it easier to understand. Let's put the checking requirements in comment in `__init__.py`

```python
    # if not is_github_hook(request):
    #     return ('Nothing to see here', 401, {'Content-Type': 'text/plain'})
```

Then let send a [webhook.json](https://gist.github.com/karlcow/ead3caa7cb567533d9684d97e950ef14) payload.

So we got 

```
<Response [404]>
['__attrs__', '__bool__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getstate__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', '_content_consumed', 'apparent_encoding', 'close', 'connection', 'content', 'cookies', 'elapsed', 'encoding', 'headers', 'history', 'is_permanent_redirect', 'is_redirect', 'iter_content', 'iter_lines', 'json', 'links', 'ok', 'raise_for_status', 'raw', 'reason', 'request', 'status_code', 'text', 'url']
--------------------------------------------------------------------------------
INFO in __init__ [/Users/karl/code/webcompat.com/webcompat/webhooks/__init__.py:53]:
failed to set labels on issue 14012
--------------------------------------------------------------------------------
127.0.0.1 - - [06/Dec/2017 16:02:36] "POST /webhooks/labeler HTTP/1.1" 400 -
```

* `<Response [404]>` is the first print.
* The list  of methods is the second print with `dir`. 

So everything is normal. It returns 404 as expected because we used a payload which is good for web-bugs and not webcompat-tests. Ultimately it should replied with a 401 from GitHub.

but at this stage it doesn't matter.

```python
    print(update_response)
    print(update_response.headers)
    print(update_response.text)
``` 

will send back

```
<Response [404]>

{'Status': '404 Not Found', 'X-RateLimit-Remaining': '4998', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-Runtime-rack': '0.029428', 'Content-Security-Policy': "default-src 'none'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'Transfer-Encoding': 'chunked', 'X-GitHub-Request-Id': 'C337:5BEA:1EC1B84:4C692CF:5A27974F', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-XSS-Protection': '1; mode=block', 'Server': 'GitHub.com', 'X-Content-Type-Options': 'nosniff', 'X-RateLimit-Limit': '5000', 'Content-Encoding': 'gzip', 'Date': 'Wed, 06 Dec 2017 07:08:00 GMT', 'X-OAuth-Scopes': 'gist, repo, user', 'Content-Type': 'application/json; charset=utf-8', 'X-Accepted-OAuth-Scopes': 'repo', 'X-Frame-Options': 'deny', 'X-RateLimit-Reset': '1512547356'}

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}
--------------------------------------------------------------------------------
```

So I guess our test should be something along that when we give a payload to `new_opened_issue()` the result is 

* an HTTP response
* a JSON file
* status_code being 200 or 4* class.

but we could probably make this a bit more testable in another way by separating the tuple from the request.

* `new_opened_issue()` gets a payload
* it calls a function to create a tuple `({'labels': labels, 'milestone': milestone}, issue_number)`
* then `new_opened_issue` creates the request taking the code from `update_issue()`
* and we scrape `update_issue`. 

We still need the test for `new_opened_issue()` but we can better test the sequence call generating the tuple and make it easier to test different type of tuples.
