### ISSUE TITLE
Investigate "browser-firefox-mobile-nightly-59.0a1" label on issue

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1971]
I don't know why this label would be applied, rather than just `browser-fireffox-mobile`. We have a few `firefox-mobile-nightly` labeled issues as well: https://github.com/webcompat/web-bugs/labels/browser-firefox-mobile-nightly

https://github.com/webcompat/web-bugs/issues/14071 is the issue reported by @softvision-oana-arbuzov.

Here's the comment metadata:

```
<!-- @browser: Firefox Mobile Nightly 59.0a1 (2017-12-04) -->
<!-- @ua_header: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 -->
```

Maybe the user added it manually to the browser field? Something for us to normalize in webhook/labeler code.

**Comment by karlcow** [comment]
<img width="738" alt="capture d ecran 2017-12-07 a 00 06 06" src="https://user-images.githubusercontent.com/505230/33668221-78048016-dae2-11e7-9e83-e57179ac2ad0.png">

**Comment by miketaylr** [comment]
I wonder if fixing https://github.com/webcompat/webcompat.com/issues/1949 would solve this... if `@browser` only ever contained the name, presumably version info and dates wouldn't sneak in.

**Comment by karlcow** [comment]
```python
>>> browser = 'Firefox Mobile Nightly 59.0a1 (2017-12-04)'
>>> import re
>>> re.search(r'([^\d]+?)\s[\d\.]+', browser)
<_sre.SRE_Match object at 0x101a4fd50>
>>> browser = browser.lower()
>>> browser = browser.rsplit(' ', 1)[0]
>>> browser
'firefox mobile nightly 59.0a1'
>>> browser = browser.encode('utf-8')
>>> browser
'firefox mobile nightly 59.0a1'
>>> browser = browser.translate(None, '()')
>>> browser
'firefox mobile nightly 59.0a1'
>>> dash_browser = '-'.join(browser.split())
>>> dash_browser
'firefox-mobile-nightly-59.0a1'
>>> 'browser-{name}'.format(name=dash_browser)
'browser-firefox-mobile-nightly-59.0a1'
```

The `browser.rsplit(' ', 1)[0]` doesn't answer this use case.

**Comment by karlcow** [comment]
yes I want to rationalize things and probably #1949 can solve it. I could propose something tomorrow.

**Comment by miketaylr** [comment]
I completely forgot that we trust user input for the label here... I'm surprised this hasn't been abused yet. >_<

**Comment by karlcow** [comment]
> I completely forgot that we trust user input for the label here... I'm surprised this hasn't been abused yet. >_< 

I created a new issue #1973 and its associated pull request #1974 before solving this one here. 
We problably should fix in #1949 if we think that version-less are ok.

**Comment by karlcow** [comment]
Another one from #15014

<img width="601" alt="capture d ecran 2018-01-23 a 13 53 47" src="https://user-images.githubusercontent.com/505230/35258757-f14ebaa4-0044-11e8-979b-01c2ec06de8f.png">

**Comment by miketaylr** [comment]
I wonder what the best way to fix this is. It seems tricky if we want webcompat-bot to be "smart" and create labels where they don't exist yet (so we don't have to update whitelists or create labels ourselves)

One lazy, not-bullet-proof solution is to reject output that doesn't match `[a-z\-]`. You could still end up with garbage... but maybe less?

**Comment by karlcow** [comment]
Could the solution be to think the other way around?
And have python manage the node environment?

See http://jsatt.com/blog/virtualenvs-for-all/
and https://github.com/ekalinin/nodeenv

**Comment by karlcow** [comment]
Our current UI is
<img width="452" alt="capture d ecran 2018-05-09 a 16 24 46" src="https://user-images.githubusercontent.com/505230/39801256-8b29e708-53a5-11e8-9b89-77c2b6ca7d9d.png">

This is editable by a Human

https://staging.webcompat.com/issues/1499

<img width="486" alt="capture d ecran 2018-05-09 a 16 28 01" src="https://user-images.githubusercontent.com/505230/39801398-faa5aa7c-53a5-11e8-9a30-c817d129c173.png">

no labels have been assigned, because not part of the matching rules.

Let's see
https://staging.webcompat.com/issues/1501
ooopsie. I put in the form:

'Space (Lolipop) 49 and Punk Cat Space' and we end up with 
https://github.com/webcompat/webcompat-tests/labels/browser-%27space-lolipop-49-and-punk-cat

<img width="911" alt="capture d ecran 2018-05-09 a 16 35 30" src="https://user-images.githubusercontent.com/505230/39801697-07026b56-53a7-11e8-9c90-d83a992c82ef.png">




https://github.com/webcompat/webcompat.com/blob/c122e27fca01816fb6d86e2284f902684b7addab/webcompat/webhooks/helpers.py#L35-L47

**Comment by karlcow** [comment]
Maybe what we can do as a poor man option, but better than nothing.

We currently have two values:
* The actual browser from where the issue is being reported
* The browser name typed by the reporter.

1. If the two are identical, we let the webhooks do its job
2. If they differ, we tag with a browser-fixme label
  
The information is already there in the bug report in plain-text. 
https://staging.webcompat.com/issues/1501

The fixme will just help to double check which ones need an additional check.

@softvision-oana-arbuzov @softvision-sergiulogigan What do you think?

**Comment by karlcow** [comment]
I adopted a different strategy. To simplify a bit things.

**Comment by softvision-sergiulogigan** [comment]
> The actual browser from where the issue is being reported
> The browser name typed by the reporter.

We do this all the time. We always log issues on webcompat.com using the Desktop (Windows 10), even if the issue itself comes from Mobile, MacOS, Linux etc.

I think that the most relevant information is what the user types in the "Is this information correct?" field.



> The fixme will just help to double check which ones need an additional check.

I wonder how much overhead will this create. I'm guessing this will not be an automated process.
