### ISSUE TITLE
[triage dashboard]:  How to handle empty priority?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2032]
For an issue without a priority label (uh, unsure if we broke this, but I think it's possible not every issue will end up with one), we show an empty *Priority:*

Maybe we could have the strong "none" or not show it if there's no priority?

![screen shot 2018-01-23 at 10 08 46 am](https://user-images.githubusercontent.com/67283/35286409-90ec2c6a-0025-11e8-8244-c884ed330da6.png)

cc @magsout @karlcow

**Comment by miketaylr** [comment]
> unsure if we broke this

(nah, it's working, just some issues don't get a priority.)

**Comment by karlcow** [comment]
Thanks @miketaylr. Yup a bug.

**Comment by magsout** [comment]
@karlcow @miketaylr hum sorry, not sure to understand.

**Comment by miketaylr** [comment]
> @karlcow @miketaylr hum sorry, not sure to understand.

Sorry, I could do better in explaining.

An issue will sometimes have a `priority-foo` label. If it does, the card will show the priority. If it doesn't, it just says `Priority`.

So we should probably leave a message like "Priority: none" or something to fix this.

(check out the screenshot in the original description).

**Comment by karlcow** [comment]
This is dependent on #2033 
I start to have an idea of making everything a bit more eye-candy and compact.

**Comment by zoepage** [comment]
What's the status of this issue? :)

**Comment by karlcow** [comment]
ok this still needs to be solved :)

**Comment by karlcow** [comment]
@magsout we haven't solved this one yet.

**Comment by karlcow** [comment]
Right now in the data, we send to the templates: `priority: True` or `False`.

Ah waiiiiiiit… just understood the misunderstanding!!!
ahah.

@miketaylr this Priority is not the priority you think.

https://github.com/webcompat/webcompat.com/blob/82f1e7fb8cb40678ed77c4727054f035e241957e/webcompat/dashboard.py#L28-L29

This priority is the issue is older than 48h. :)

ok let's turn this into a proposal.

<img width="965" alt="capture d ecran 2018-02-22 a 16 53 10" src="https://user-images.githubusercontent.com/505230/36526266-e67bee4e-17f0-11e8-9d64-ff727cbcd901.png">

which would be one line change in 

```html
            <div class="wc-Triage-metas-infos">
              {% if issue['priority'] %} ⚠️ {% endif %}
              {% if issue['needinfo'] %} - Needinfo {% endif %}
            </div>
```

https://github.com/webcompat/webcompat.com/blob/82f1e7fb8cb40678ed77c4727054f035e241957e/webcompat/templates/dashboard/triage/needstriage-list.html#L193-L196

Now if you would like to have the actual priority too, we can bring that in a new bug. :)

**Comment by magsout** [comment]
@karlcow we can add an icon for need information too, though ?

**Comment by karlcow** [comment]
yup. 🕐 or 🛎 or ⏰ or …?

**Comment by miketaylr** [comment]
@karlcow what does Priority mean? Maybe we need a more clear wording, or at least a key at the bottom. :)

**Comment by miketaylr** [comment]
Ah wait, you already said:

> This priority is the issue is older than 48h. :)

I think we should have an icon ( i like ⏰, but i don't care), and at the bottom of the page have something like:

> ⏰: Untriaged issues older than 48 hours.
