### ISSUE TITLE
Form validation checkmarks appear broken

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2073]
STR:

1. go to https://staging.webcompat.com/issues/new
2. clear out browser and OS
3. add something to the browser field

Expected:

there should be a green checkmark in one

Actual:

there's a green checkmark in both fields now

Note: this appears to be a bug on the existing webcompat site, so something we regressed at some point.

**Comment by softvision-oana-arbuzov** [comment]
Reproducible also on Mobile.
Note: this issue is reproducible also on webcompat.com site. 
![screenshot-1519035397436](https://user-images.githubusercontent.com/12184325/36372780-bd7a677a-156e-11e8-937a-8a30cf4db022.jpg)

Affected area:
```html
<div class="form-text form-element js-Form-group is-validated js-no-error">
	<label class="form-label" for="browser">Is this information correct?</label>
	<input class="form-field text-field" id="browser" name="browser" value="Firefox Mobile 60.0" type="text">
		<span class="form-input-validation check"></span>
	<input class="form-field text-field" id="os" name="os" value="Android 8.1.0" type="text">
		<span class="form-input-validation check"></span>
</div>
```

Field input:
```js
function r() {
  return (this && this !== Vn && this instanceof r ? e : n).apply(t, arguments)
}
```

**Tested with:**
Browser / Version: Firefox Nightly 60.0a1 (2018-02-18) (Mobile)
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Comment by zoepage** [comment]
@miketaylr didn't we merge this last week? 🤔

**Comment by zoepage** [comment]
I should have read your first comment more properly. Sorry.
As this got fixed in the refactor branch and we'll deploy soon, shall we close this or do you rather want to leave it open?

**Comment by zoepage** [comment]
closing as this has been merged

**Comment by miketaylr** [comment]
> closing as this has been merged

SGTM!

(sorry for not catching your ping here)
