### ISSUE TITLE
Top menu on "Contributors" page should be fully highlighted and separated

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2146]
URL: https://staging.webcompat.com/contributors  
Browser / Version: Firefox Nightly 60.0a1 (2018-02-18) (Mobile), Chrome 64.0.3282.137 (Mobile). 
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/contributors
    2. Observe top menu layout.

**Expected Behavior:**
    The white highlight area is displayed on the entire page and separator is available between the menu and the sections.

**Actual Behavior:**
    The white highlight area is cropped and no separator is available between the menu and the sections.

**Note**
    1. Not reproducible on Desktop.
    2. On Chrome the arrows exceed the white highlight area.
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

Modified white highlight `background-color` to be more visible for testing purpose. 

![screenshot-1519029582976](https://user-images.githubusercontent.com/12184325/36369036-7421c066-1562-11e8-932a-ef566f5b8dc6.jpg)

**Comment by zoepage** [comment]
This needs to be fixed. I'll assign myself.

**Comment by Regaddi** [comment]
I stumble across a chain of issues here, all regarding the grid and its usages:

1. We can change the `x1-fix` class on the "Join us" tile to `x1`, then we'd have this tile nearly stretched to the edge.
2. The second tile "The Project" is not fully stretched, because of `.x2 { max-width: var(--unit-modul-m); }`. We can set this to `--unit-modul-l`, just like in `x1`.
3. The `margin-right` set in `.bio .grid-nested:first-child, .grid-cell` prevents a full stretch of x1, but seems to be needed on every `grid-cell`!?
4. To prevent overlapping `margin-right` in any constellation, we could change the grid gutter to be double-sided (margin-left & margin-right) and add negative margins on `grid-row`.
5. This destroys current different usages of the grid (e.g. the bio grid on contributors page), because there are different background settings for `grid` and `grid-show-gap`.

For me it looks, like the current grid doesn't fit all needs.

I'd recommend a grid refactor.

@zoepage ?

**Comment by zoepage** [comment]
I agree, the grid needs to be extended here.
I'll try to add a bit more context. I hope, this might be helpful.

We've build the grid as simple as possible, which is limiting, but we tried it to be as easy to understand and reuse as possible for others. This also means, we did not cover all use cases that might show up.

The sub navigation for the content was added later on and also re-written. The 1:2, 3 layout was more like a `Bob Ross - happy accident` we liked and decided to keep it. It definitely has flaws. So, if you feel like you would be able to change the module and make it work for our needs, feel free! Please just keep in mind that we want to make sure to not change any basic behaviour of the grid.

Suggestion: As this sub-nav is a special use case, feel free to change `grid-show-gap` to a different class and scope from there?

What do you think?
