### ISSUE TITLE
Remove travis branch build restrictions

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2181]
https://github.com/webcompat/webcompat.com/blob/master/.travis.yml#L5-L6

I think it's harmful that we're not building PRs against other branches. Since it doesn't cost us anything, I think we should go back to building every PR.

WDYT @zoepage? @denschub?

**Comment by denschub** [comment]
My reasoning behind initially building only the master branch were outlined in #1909. We had known failures in the refactor branch, which caused a lot of emails whenever someone opened a PR against that, which was kind of annoying.

I don't think it is really harmful not to build PRs for all branches by default, especially since this is a thing that usually should not even happen. PRs should always be targeted towards one branch, which usually is the master branch. Of course, we have a little bit of a different situation right now, since PRs are targeted against the `refactor` branch as well. We may very well enable the refactor branch as a target. I personally still don't think we should build all branches, especially since the usual pattern in this project is to allow people to push their development branches upstream, which would trigger a build whenever someone updates their branches, and then build it again once the PR is opened.

> Since it doesn't cost us anything

Right, that's actually kinda the point. :) We're running our builds on free infrastructure donated by a company that offers the same services paid. If everyone tries to reduce the number of build jobs to only the required amount, it makes supporting this community infrastructure easier, and ultimately is the way to make sure we have a free build service in the future. If everyone would simply spam jobs, the free Travis service would not be sustainable.

It's a bit comparable to the issues with the Gecko try servers some years ago, where everyone just pushed everything to try and the backlog was so high that it never got to building all jobs. As soon as people started to really think about whether they *need* to build something remotely or not, the backlog got manageable again. *However*, since the overall traffic in this project is really low, I am not going to be sad if we enable builds for everything.

Initially, limiting the build branches was only a workaround to save us a lot of email traffic during the sprint and the weeks after, and we can revert that now. But I wanted to outline my reasoning for not simply building everything.

**Comment by denschub** [comment]
Also, I totally did not mean to close this issue. Sorry for that.

**Comment by zoepage** [comment]
I agree to mostly everything Dennis said. We should not build every branch, but adding refactor (until this is finally merged) seems like a very good idea especially as the test are passing almost.

So, +1 on adding refactor to the config.

**Comment by zoepage** [comment]
@miketaylr did you add the `refactor` branch on master to the config? I can see the change, but there is not commit referencing this issue? Just the commit of the `testing` branch.

**Comment by miketaylr** [comment]
> Right, that's actually kinda the point. :) We're running our builds on free infrastructure donated by a company that offers the same services paid. If everyone tries to reduce the number of build jobs to only the required amount, it makes supporting this community infrastructure easier, and ultimately is the way to make sure we have a free build service in the future. If everyone would simply spam jobs, the free Travis service would not be sustainable.

I don't think we're spamming builds. We're running tests on branches that we're actively developing. Also, if this becomes an issue for Travis and they want to charge for it. I'm happy to pay. For now, they don't. Considering our actual usage vs large projects with large matrices of builds... I can't imagine we're even close to a drop in the bucket of overhead.

> @miketaylr did you add the refactor branch on master to the config? I can see the change, but there is not commit referencing this issue? Just the commit of the testing branch.

I did @zoepage. https://github.com/webcompat/webcompat.com/commit/82f1e7fb8cb40678ed77c4727054f035e241957e

**Comment by denschub** [comment]
> I don't think we're spamming builds.

We definitely were during the sprint weekend. :) But yeah, we don't do that on a regular basis.

**Comment by miketaylr** [comment]
I think once refactor lands, this issue won't be so important. Let's close it for now because there's more imporant problems to worry about. Thanks for input @zoepage and @denschub
