### ISSUE TITLE
CSP blocking script

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2196]
@miketaylr I get following error:

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.`

Do you see it?

**Comment by miketaylr** [comment]
I do! I believe that's from jQuery. Let me try to find a reference to the Bugzilla bug.

(we can probably close this as invalid)

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1336076#c6

> It's an unfortunate combination of any site running latest Firefox, jQuery 1.x and a sane CSP;
As far as I can see I have no other option than patching jQuery 1.x to change their test:

> https://github.com/jquery/jquery/blob/1.12-stable/src/event/support.js#L17

If we care about this, we can morph this bug to upgrade jQuery versions (assuming some later version has a different feature test). But I wouldn't consider it a real bug or important, just some console spam due to our strict CSP policy.

**Comment by miketaylr** [comment]
(removing refactor scope because this exists in production as well)

**Comment by miketaylr** [comment]
I think let's just WONTFIX.
