### ISSUE TITLE
The "Older than 48h" bucket in NeedsTriage Dashboard should not take into consideration issues with "Needsinfo"

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2215]
Mike sent us an e-mail, saying that "I thought if an issue had a “needs info” label, it shouldn’t appear in the “older than 48” bucket… if that’s not the case currently, that’s a bug."

https://webcompat.com/dashboard/triage

**Comment by karlcow** [comment]
ok let's go back to the original agreement.

https://github.com/webcompat/webcompat.com/issues/1859#issuecomment-343044969

>     I also propose we keep the needinfo issues but we make them hidden by default through css in the page with possibility to show them ( ping @miketaylr )

So yes indeed the logic of the filter is not correct here.

@magsout 

1. The default view should not show the `needinfo` issue
2. The needinfo selector should **add** the needinfo issues to the full view and not select only the needinfo ones. 

I can try to fix it in https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/dashboard.js

(good exercise for me, that will force me a bit to go deeper in the JS).

**Comment by magsout** [comment]
@karlcow so point 1 is ok. By default needinfo's issues are hidden by default. But point 2 is not ok. We have to show all issue in point 1 and in addition the needinfo issues?

**Comment by karlcow** [comment]
@magsout for 1, are you sure? 

Check this https://staging.webcompat.com/dashboard/triage
<img width="663" alt="capture d ecran 2018-03-12 a 23 05 00" src="https://user-images.githubusercontent.com/505230/37288131-d2e119ec-2649-11e8-8079-62b5df8bad8b.png">

**Comment by magsout** [comment]
@karlcow you’re right. The logic of filter is not correct. basically If an issue is in state priority, it’s render whatever if the issue is in state needinfo or not.

If I understand well, all issues are in state priority, and some of them are `needinfo`. 

```html
<div class="wc-Triage-metas-infos">
  {% if issue['priority'] %} Priority {% endif %}
  {% if issue['needinfo'] %} - Needinfo {% endif %}
 </div>
```
In the first case we have to display priority’s issues but exclude issues in state needinfo.
In the second case we have to display issues only in state needinfo (priority or not)?

**Comment by magsout** [comment]
So here the logic https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/dashboard.js#L98-L105
When a select is handle, the JavaScript checks the value of the option and test if the element has the className, if not the JS hides the element.

So we need to improve this part and add another logic. Maybe it would be better to add `data-*` instead of class. We take the name of the select, search the `data-name` and if the value match exactly with the value option we allow the render of the issue. Of course we have to add another function because this logic is only for state and not for browsers as we do for `filteringSort()`

@karlcow thought ?

**Comment by karlcow** [comment]
I will check this tomorrow (Friday, March 16) in details. Sorry for not replying before. I had forgotten.

**Comment by karlcow** [comment]
ok it's what we send to the template:


```python
[
    {
        'needinfo': False, 
        'title': u'checking labels with new triage tag', 
        'created_at': u'2016-06-06T04:17:28Z', 
        'updated_at': u'2017-11-08T06:25:36Z', 
        'number': 404, 
        'priority': True, 
        'browsers': []
        }, 
    {
        'needinfo': False, 
        'title': u'functional test Search Auth Search Works', 
        'created_at': u'2016-06-10T01:23:33Z', 
        'updated_at': u'2017-11-08T06:25:36Z', 
        'number': 406, 
        'priority': True, 
        'browsers': []
        },
    …
    ]
```

Then we use needstriage-list.html to put the data in, which gives:

```html
<article data-number="486" class="wc-Triage priority firefox" style="order: 3;">
    <div class="wc-Triage-container">
      <h2 class="wc-Triage-title">
        <a href="/issues/486" title="codepen.io - video doesn't play">
          486: codepen.io - video doesn't play
        </a>
      </h2>
      <div class="wc-Triage-wrapper">
        <div class="wc-Triage-infos">
          <div class="wc-Triage-metas">
            <div>
              Created:
              <time class="wc-Triage-date" datetime="2016-10-19T09:56:43Z">2016-10-19</time>
            </div>
            <div>
              Updated:
              <time class="wc-Triage-date" datetime="2018-02-19T15:03:45Z">2018-02-19</time>
            </div>
            <div class="wc-Triage-metas-infos">
              <span title="More than 48h old"> ⏰ </span>
              <span title="Waiting for info"></span>
            </div>
          </div>
        </div>
        <footer class="wc-Triage-footer">
          <div>    
              <span>firefox&nbsp;</span>
          </div>
        </footer>
      </div>
    </div>
  </article>
```

The render logic for the first page should be:

So we can modify the default template needstriage_list to be

```html
<article
    data-number="{{ issue['number'] }}"
    class="
      wc-Triage
      {% if issue['priority'] %} priority {% endif %}
      {% if issue['needinfo'] %} needinfo {% endif %}
      {% for browser in issue['browsers'] %}
        {{ browser }}
      {% endfor %}
    "
    {% if issue['needinfo'] %} hidden {% endif %}
  >
```

It means it will be at first sight something like this:


```html
<article data-number="486" class="wc-Triage priority firefox needinfo" hidden>
```

So the default view is fixed. Then for rendering when selecting the needinfo, we just need to remove the hidden where article contains 

<img width="1123" alt="capture d ecran 2018-03-16 a 16 12 58" src="https://user-images.githubusercontent.com/505230/37508101-f4d172ca-2934-11e8-8b43-4c428bb9820b.png">


```js
var issues_needinfo = document.getElementsByClassName('needinfo');
for (let issue of issues_needinfo) {
    issue.removeAttribute('hidden');
}
```

This will reveal the full list with needinfo items.

And if @miketaylr meant to show only the needinfo. We just need to hide the ones without needinfo and reveal the ones with needsinfo.

```js
var issues = document.getElementsByClassName('wc-Triage');
for (let issue of issues) {
    if (!issue.classList.contains('needinfo')) {
        issue.setAttribute('hidden', '');
    } else {
        issue.removeAttribute('hidden');
    }
}
```

**Comment by karlcow** [comment]
@magsout I hope it's not too naive. My JS being rudimentary, but always happy to learn more.

**Comment by miketaylr** [comment]
> And if @miketaylr meant to show only the needinfo. We just need to hide the ones without needinfo and reveal the ones with needsinfo.

This sentence is a little hard for me to parse, but to clarify what I believe we want:

Dashboard by default does not include "needsinfo" issues in count of issues that need triage, or issues older than 48 hours (just like the comment 0 of this report). 

And yeah, it should be possible to display the needsinfo issues via the filter. I don't have opinions whether or not it's more useful to only display them, or include them.

**Comment by karlcow** [comment]
>  Dashboard by default does not include "needsinfo" issues in count of issues that need triage 

(The list) This understood and in the fix

> or issues older than 48 hours (just like the comment 0 of this report).

Ah you want to remove them from the total count box too. :) ok.

**Comment by karlcow** [comment]
@miketaylr 

Let's try again with easy to parse  things (hopefully) ;)

@ magsout Because I think we are not talking about the same thing. if I understood now, @softvision-sergiulogigan and @miketaylr seem to be talking about the boxes, not the list.

## Current state:

1. Big first box: Total number of issues in needstriage https://github.com/webcompat/web-bugs/milestone/2 (including needinfo)
2. Second big box: Total number of issues **older than 48h** (including needinfo)
3. List by default: Everything **older than 48h** (including needinfo) https://github.com/webcompat/web-bugs/milestone/2

## Future state:

@miketaylr @softvision-sergiulogigan Would this address your concerns?

1. Big first box: Total number of issues in needstriage (excluding needinfo ones)
2. Second big box: Total number of issues **older than 48h** (excluding needinfo ones)
3. List by default: Everything **older than 48h** (excluding needinfo)
4. List with needinfo selected: Only the needinfo.

**Comment by softvision-sergiulogigan** [comment]
@karlcow , @magsout 

> Future state:
> @miketaylr @softvision-sergiulogigan Would this address your concerns?
> 
> Big first box: Total number of issues in needstriage (excluding needinfo ones)
> Second big box: Total number of issues older than 48h (excluding needinfo ones)
> List by default: Everything older than 48h (excluding needinfo)

I think this is spot on!


> List with needinfo selected: Only the needinfo.

I think that we should have the current state (all issues that have NeedsTriage label, or as detailed in the previous comment, "Current state" section) when selecting the option to include the needinfo state.

@miketaylr do you agree?

**Comment by miketaylr** [comment]
Yep, agree with @softvision-sergiulogigan. Thanks for articulating clearly @karlcow.

**Comment by magsout** [comment]
thanks everybody for your comments.

>I think that we should have the current state (all issues that have NeedsTriage label, or as detailed in the previous comment, "Current state" section) when selecting the option to include the needinfo state.

Sorry, but not sure to well understand this comment?

case 1,2,3 are ok for you?

It's just about 4) ?

**Comment by karlcow** [comment]
They want 1, 2, 3 from Future State.
AND
4 is 1 + needinfo

aka 

```js
var issues_needinfo = document.getElementsByClassName('needinfo');
for (let issue of issues_needinfo) {
    issue.removeAttribute('hidden');
}
```

I'll propose a PR tomorrow.

**Comment by magsout** [comment]
Thanks @karlcow <3
