### ISSUE TITLE
label box floating broken on stage

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2245]
As you can see here: https://staging.webcompat.com/issues/1390 the label box is not on the right side anymore. 

Seems like an issue introduced before that appeared after we merged.

@magsout @Regaddi Any idea?

**Comment by Regaddi** [comment]
That's an evil one.

[Here](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L518) the issue is made visible with `.fadeIn()`. This sets inline styles `display: block; zoom: 1;`. And that breaks our beautiful flexbox styles.

Possible solutions:

1. Instead of `.fadeIn()` call `.removeClass("is-hidden")` <-- touch JS
2. Set CSS style `display: flex` to `display: flex !important` <-- ugly

**Comment by zoepage** [comment]
Oh wow. That makes sense... I'd say we remove the class for now to quick fix. And re-open the original issue that introduced that bug

**Comment by miketaylr** [comment]
> Instead of .fadeIn() call .removeClass("is-hidden") <-- touch JS

This seems reasonable.

**Comment by zoepage** [comment]
merged #2246
