### ISSUE TITLE
Icons are not displayed on Safari (Mobile + Desktop)

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2255]
Hmm, I already opened a problem about this bug? I think it's something about CSP , no? 

On iOS with Firefox and Safari, the icons are not displayed

![img_0441](https://user-images.githubusercontent.com/1997108/37546542-8cee27b4-296d-11e8-81aa-b97cbb22484f.PNG)

**Comment by magsout** [comment]
found it https://github.com/webcompat/webcompat.com/issues/1647

**Comment by zoepage** [comment]
Interesting... @miketaylr did you see that already before? Like is this a known issue?

**Comment by miketaylr** [comment]
> Interesting... @miketaylr did you see that already before? Like is this a known issue?

@zoepage I think this is a new bug (at least, not previously reported). Probably P0?

**Comment by miketaylr** [comment]
Not just iOS, Safari as well:

![screen shot 2018-03-19 at 2 26 43 pm](https://user-images.githubusercontent.com/67283/37617663-c458ce00-2b81-11e8-99de-0dca848c1e58.png)

**Comment by miketaylr** [comment]
Using `xlink:href` instead of `href` will fix this issue, @zoepage.

![screen shot 2018-03-19 at 2 39 12 pm](https://user-images.githubusercontent.com/67283/37618166-594aee5c-2b83-11e8-9c42-3d841ea8a26c.png)

![screen shot 2018-03-19 at 2 40 33 pm](https://user-images.githubusercontent.com/67283/37618205-808d5144-2b83-11e8-8727-dcef8ed1f966.png)

**Comment by magsout** [comment]
@miketaylr oh good catch.
