### ISSUE TITLE
Move `wc-Comment-content-nsfw`to new CSS

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2320]
Looks like we did not think about https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L304 and should add that functionality to the new CSS.

**Comment by miketaylr** [comment]
Permalink here: https://github.com/webcompat/webcompat.com/blob/173d09289eac42c6aa2b679850204663dd3b2f02/webcompat/static/js/lib/issues.js#L334

**Comment by karlcow** [comment]
This doesn't change anything in the interactions. This is about consistency in naming.

**Comment by marimeireles** [comment]
Hi!
Can I take this?

**Comment by magsout** [comment]
@marimeireles sure, let me know if you need help!

**Comment by marimeireles** [comment]
I do, thanks @magsout 
I'm a little confused about where I should make the changes.
I believe that I should copy the code below, paste it and adapt it, if needed, in the new CSS version, right?
https://github.com/webcompat/webcompat.com/blob/2c03283cd553d6d0ad094f6c46d8673b8b544d1d/webcompat/static/css/development/components/markdown.css#L44-L73 
But I'm not sure where to put it since the file where it used to be, `webcompat/static/css/development/components/markdown.css`, was deleted in the new CSS version ([this commit](https://github.com/webcompat/webcompat.com/commit/9d55df25fa2e126082b073579efa9559404b2a1c#diff-6bf3a83bda5a5c6f5f5e8492aa9cc7de)).

**Comment by magsout** [comment]
@marimeireles 
>I believe that I should copy the code below, paste it and adapt it, if needed, in the new CSS version, right?

Yes, exactly. All the logic about NSFX was removed with the new version of webcompat. Only the `className` in the JS still exist.

1) change the name of the className in the JS file
2) re-use the old css and adpat it with the new css atomic js

**Comment by magsout** [comment]
@marimeireles you could write the css there https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/src/issue.css

**Comment by marimeireles** [comment]
That's where I thought, but I wasn't sure.
Thanks! I'll try to solve it :)
