### ISSUE TITLE
App fails to start because it doesn't know about a milestone

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2411]
I just deployed v9.0.5, and noticed webcompat.com production was returning 500.

Checking uwsgi logs:

```
Traceback (most recent call last):
  File "./webcompat/__init__.py", line 20, in <module>
    app.config.from_object('config')
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 406, in import_string
    return __import__(import_name)
  File "./config/__init__.py", line 151, in <module>
    if not initialize_status():
  File "./config/__init__.py", line 62, in initialize_status
    app.config['STATUSES'] = convert_milestones(milestones_content)
  File "./config/__init__.py", line 85, in convert_milestones
    STATUSES[milestone['title']]['id'] = milestone['number']
KeyError: u'work'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

There was a `work` milestone that someone created 10 hours ago (probably on accident, it's pretty easy to do this in github's interface). And I guess we failed hard. 💣

**Comment by miketaylr** [comment]
How did this bug even manifest? Is this a race condition? If it was trying to read from the milestones on disk (which wouldn't have a 'work' milestone), how would it even know about 'work' to throw a KeyError? Confusing.

**Comment by karlcow** [comment]
ok I'll check that today. No good. And the way we instantiate milestone is weird anyway (my bad and already commented on that in a previous issue.)

**Comment by karlcow** [comment]
Ah this happened here.
<img width="742" alt="capture d ecran 2018-04-20 a 09 29 34" src="https://user-images.githubusercontent.com/505230/39024670-663de32c-447d-11e8-9f0e-d1f53f78375b.png">

Because you manually type the milestone in Github. You may accidently create another milestone with the editor.

<img width="353" alt="capture d ecran 2018-04-20 a 09 30 26" src="https://user-images.githubusercontent.com/505230/39024706-9752aaba-447d-11e8-895e-f1549ef9cd8d.png">

ok so understood the source of the breakage. Let's make the code more robust so that the 500 doesn't happen in case this happens again.

**Comment by karlcow** [comment]
ok this is happening in there.

https://github.com/webcompat/webcompat.com/blob/99210fd9e5467ca83f750ee45f97a16f842944d5/config/__init__.py#L81-L86

STATUSES are defined in 

https://github.com/webcompat/webcompat.com/blob/99210fd9e5467ca83f750ee45f97a16f842944d5/config/environment.py#L25-L40

Two ways this can fail. 

* Adding a new milestone.
* Removing a milestone.
