### ISSUE TITLE
The bug reporting/comments area is not automatically expanded

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2422]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 61.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com/issues/new
2. Type a lot of text in the "What steps did you take before this problem occurred?" field.

**Expected Behavior:**
The bug reporting/comments area is automatically expanded to accomodate the text typed.

**Actual Behavior:**
The bug reporting/comments area is not automatically expanded.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/39198508-efe25aa2-47ef-11e8-88e3-0247ec522467.png)

**Comment by zoepage** [comment]
After various bugs and a longer discussion with e.g. @karlcow we decided to remove the feature a few weeks ago.

**Comment by karlcow** [comment]
Link to previous discussion:

* Remove autoExpand feature for textareas #1636 
* Comment box issues with long comments #1622 
* auto-expand the bug reporting/comments area #1211 

Here an example of code with plain JS.
https://jsbin.com/qizepev/edit?html,css,js,output

There are indeed issues with auto-expand, which mainly appears when having a smaller viewport. Which is unfortunate because it's not possible to resize on mobile 😭 and "4 lines"-area is small.

Note also that the issues in #1622 had 4 issues into it. Some are still not addressed. So not everything is related to the auto-expand feature.

Does anyone know a Web site where this is done well?

We could also instead of auto expand have a much longer area for this section. 
We could imagine to have 20 lines by default. **Every single time, I resize the textarea**, be in comments or report form. Surface of readability. Same principle than using a wide paper map gives you a better understanding of a geographical space than on a small mobile screen.

**Comment by karlcow** [comment]
@softvision-sergiulogigan @softvision-oana-arbuzov Instead of jumping to a UX/technical solution, could you just describe what would be more comfortable for you when typing a comment or/and filing a form?

**Comment by miketaylr** [comment]
If we removed it due to bugs, I'm not opposed to someone trying again, learning from the first attempt's lessons. 

It seems useful, and if some of our biggest customers (do we have a bug reporting hall of fame yet??) are indicating that the current situation isn't great for them, it's a strong signal.

**Comment by softvision-sergiulogigan** [comment]
I think having an auto-expandable reporting/comments area would improve overall bug quality. You'd be able to re-read your filed issue or comment before submitting it, without manually resizing the text area.

Indeed, the majority of our reporters write a 1-2 line bug report, but we also have those who give meaningful contribution while reporting an issue.

Also, this can be also viewed as a site issue. It's like having a bug on Bugzilla (see the irony?)

**Comment by miketaylr** [comment]
I think it would be a good addition. Can't think of any downsides, beyond bugs in implementation.

**Comment by zoepage** [comment]
+1 on auto-expand.
Christian had an idea I liked as it solved several problems we had before; adding back the auto-expand but limiting it to a specific height. Would solve issues with scrolling (esp. on mobile), broken layout and others.

Would this work for y'all?

**Comment by Regaddi** [comment]
One thing I stumbled across while implementing the autogrow functionality:
I can easily make the textarea grow, but making it shrink back is a complete new chapter.
I'd like to clarify that we're only talking about the expansion of the textarea, not shrinking it back to fit the content.
Ok? @miketaylr @softvision-sergiulogigan @zoepage @karlcow

**Comment by karlcow** [comment]
Confirmed. No need to shrink it. 
Though maybe if we use sheep wool 🐑 and a heavy rain 🌧, we might be able to shrink it. Maybe not.

**Comment by miketaylr** [comment]
Yep, SGTM.
