### ISSUE TITLE
Labels and Milestones can be set from webcompat.com but not from Github

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2451]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 62.0a1 (Desktop)
Operating System: Windows 10

**Prerequisites:**
Login on GitHub with an account that has no priviliges set on webcompat.com project.

**Steps to Reproduce:**
1. Go to (for example) https://github.com/webcompat/web-bugs/issues/16846.
2. Observe the Labels and Status sections Gear buttons.
3. Go to (for example) https://webcompat.com/issues/16846.
4. Observe the Labels and Status sections Editor Launcher buttons.

**Expected Behavior:**
The Labels and Status sections Editor Launcher buttons are missing.

**Actual Behavior:**
The Labels and Status sections Editor Launcher buttons are displayed and functional.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![webcomp](https://user-images.githubusercontent.com/16573771/39923364-f5c30900-552b-11e8-82d3-ebe40913e22f.png)

**Comment by karlcow** [comment]
That's a good news. :)

**Comment by miketaylr** [comment]
@softvision-sergiulogigan yeah, this is by design. We wanted to create a system where contributors who aren't part of the GitHub org could move things around, or set labels.

If we have evidence of abuse, we can revisit. I think we could do a better job of being transparent about it, there isn't any real way to know who moved things or added/removed labels.
