### ISSUE TITLE
Progressive filtering doesn't work for Labels

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2453]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 62.0a1 (Desktop)
Operating System: Windows 10

**Prerequisites:**
Login onto webcompat with an account that has labels editing privileges.

**Steps to Reproduce:**
1. Go to (for example) https://webcompat.com/issues/16883.
2. Click on the Category Editor Launcher button.
3. Start typing something (eg. firefox).

**Expected Behavior:**
The Labels list is reduced to te relevant items.

**Actual Behavior:**
The list is not filtered.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/39998095-a94d3b4a-578d-11e8-95ef-eef866cfadf8.png)

**Comment by miketaylr** [comment]
I just noticed the following error in the console when testing this, seems like the root cause probably:

```
Error: Syntax error, unrecognized expression: input[name=status\: add to changelog]
```

STR:
1. go to https://staging.webcompat.com/issues/222
2.. log in
3. click on the label editor to open it, and type `type` in the filter input thingy

You should only see labels starting with `type-`, but instead I see more than that, and have that error message. So probably an issue with our regexp and escaping or whatever.

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/editor.js#L96 is the method that handles filtering.
