### ISSUE TITLE
update docs to use pip2

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2494]
After checking in with @softvision-oana-arbuzov about #2267 one of the issues was that the docs still refer to pip and not pip2 or pip3, but the scripts require pip2/3.

@karlcow am i seeing this right or should this also work with pip?

https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#detailed-setup-all-platforms

**Comment by karlcow** [comment]
Yeah. So by default now, most people use python 2.7, because it's what it is installed on their OS.
Webcompat depends on python 2.7 too. As long as one didn't install python3, things just work. What I did in #2267 is to make more explicit the commands for automatic install. We could do it in the docs too. 

(at least until we switch to python3)

Right now, python 2.7 will be retired in 1 year and 6 months, and probably OSes will also start to deprecate the default install. Maybe.
https://pythonclock.org/

We might have time to switch to python3 before that deprecation at least for security reasons (but…if we have time because there are things which are more urgent on the project than tooling. see #1332 )

So yes we could update the documentation to make it more explicit.

**Comment by miketaylr** [comment]
I'll fix this in #2267.
