### ISSUE TITLE
Triage Dashboard Needsinfo card doesn't take into account Needsinfo-xxx labels

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2511]
**Environment:**
Browser / Version: Chrome 67 (Desktop), Firefox Nightly 62.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://github.com/webcompat/web-bugs/milestone/2
2. Ctrl+F (or Command+F) needsinfo. Observe the total number of labels that contain this string.
3. Go to https://webcompat.com/dashboard/triage
4. Observe the information displayed in the Needsinfo card.

**Expected Behavior:**
To be decided.

**Actual Behavior:**
The information is not consistent. The Needsinfo-xxx labels are not taken into account.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/41657489-2fc1e790-749c-11e8-823a-d9f10ed84c95.png)

**Comment by laghee** [comment]
@karlcow It looked to me like this might be fixed by [changing this line](https://github.com/webcompat/webcompat.com/blob/d56cd783366d725bcf2cf560723a590faf41e08f/webcompat/dashboard.py#L53) to something like:
`for label in labels:`
 `if label.startswith('status-needsinfo'):`

So I tried that, but I can't get `nosetests` to run:
<img width="1173" alt="screenshot 2018-06-26 14 20 24" src="https://user-images.githubusercontent.com/20972610/41911326-9bbcdb44-794c-11e8-8f7a-445bf182d5b3.png">
 
Has something changed? Or maybe I need to monkey with my virtualenv? (All tests were running fine last week... 🤔 )

**Comment by karlcow** [comment]
@laghee on running nosetests. It's always necessary to start the virtualenv first, because the python modules are installed into the virtualenv. if `nosetests` runs outside of virtualenv it's because you also have a copy of it installed system wide. :)

**Comment by karlcow** [comment]
tests to modify 
https://github.com/webcompat/webcompat.com/blob/011183b86a75b5a64ce4a19438c58cc69d2b2240/tests/unit/test_dashboard.py#L67-L73

**Comment by laghee** [comment]
@karlcow I'm not sure I understand how we could count issues more than once if `has_needsinfo` is boolean. I did add a test case with multiple types of `needsinfo` tags to make sure it still returns `true`.

```
        labels = ['browser-safari', 'status-needsinfo', 'browser-firefox-mobile', 'status-needsinfo-karcow', 'priority-critical', 'status-needsinfo-and-guacamole']
        self.assertTrue(has_needsinfo(labels))
```

I still can't get the `nosetests` to run (they start, they just fail because python can't find the `mock` module), even though my virtualenv seems fine:
<img width="749" alt="screenshot 2018-06-27 11 25 46" src="https://user-images.githubusercontent.com/20972610/41965497-f2f7efec-79fc-11e8-8205-e921c0564b46.png">

**Comment by karlcow** [comment]
@laghee did you follow https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#installing-project-source-code

aka `pip2 install -r config/requirements.txt` **after** activatin the environment?

`ImportError` means the module has not been installed.

**Comment by karlcow** [comment]
> @karlcow I'm not sure I understand how we could count issues more than once if has_needsinfo is boolean. I did add a test case with multiple types of needsinfo tags to make sure it still returns true.

Indeed I spoke too quickly. My bad.

but that made me think a bit more:

```python
for label in labels:
    do_something()
```

the `do_something()` will execute over the full list before exiting, while we just need to have at least one needinfo in the full list. There are ways to make it a bit faster. :) Maybe with `set()`.

**Comment by laghee** [comment]
@karlcow I though I followed all the directions, and I could have sworn all the tests worked before, but my `.bash_history` doesn't go back that far, so I'm not positive. I'll try reinstalling and see if that helps!

I agree on the needless looping. I looked at `set()`, which seems like a possible solution. I guess I'd have to use `re` to match multiple possibilities? Or is there a cool way to somehow use `startswith` without referencing an individual element? (🙋 python n00b!)

Another (less pythonic, I'm sure) way would be just to return early in the `if` clause, I guess.

**Comment by karlcow** [comment]
```python
>>> import timeit
>>> labels = ['browser-safari', 'status-needsinfo', 'browser-firefox-mobile', 'status-needsinfo-karcow', 'priority-critical', 'status-needsinfo-and-guacamole']
>>> labels2 = ['browser-safari', 'browser-firefox-mobile', 'priority-critical']
>>> [label for label in labels if label.startswith('status-needsinfo')]
['status-needsinfo', 'status-needsinfo-karcow', 'status-needsinfo-and-guacamole']
>>> [label for label in labels2 if label.startswith('status-needsinfo')]
[]
>>> timeit.timeit("next((label for label in labels if 'needsinfo' in label), None)", setup='from __main__ import labels', number=1000000)
0.5575151443481445
>>> timeit.timeit("next((label for label in labels2 if 'needsinfo' in label), None)", setup='from __main__ import labels2', number=1000000)
0.36673784255981445
>>> timeit.timeit("[label for label in labels if 'needsinfo' in label]", setup='from __main__ import labels', number=1000000)
0.42851781845092773
>>> timeit.timeit("[label for label in labels2 if 'needsinfo' in label]", setup='from __main__ import labels2', number=1000000)
0.1547250747680664
```

there are probably other ways too.

Also 


```python
>>> a_list = ['foo', 'bar']
>>> if a_list: 
...     print(True)
... 
True
>>> a_list = []
>>> if a_list:
...     print(True)
... 
```

and empty list is False

**Comment by karlcow** [comment]
@laghee do your tests work now?

**Comment by karlcow** [comment]
I have found a slightly faster. Not that it matters that much, but just for the fun.

```python
>>> def test():
...     labels = ['browser-safari', 'status-needsinfo', 'browser-firefox-mobile', 'status-needsinfo-karcow', 'priority-critical', 'status-needsinfo-and-guacamole']
...     needsdinfo = (label for label in labels if label.startswith('status-needsinfo'))
...     if next(needsinfo):
...         return True
...     return False
... 
>>> def test2():
...     labels = ['browser-safari', 'status-needsinfo', 'browser-firefox-mobile', 'status-needsinfo-karcow', 'priority-critical', 'status-needsinfo-and-guacamole']
...     needsinfo = [label for label in labels if label.startswith('status-needsinfo')]
...     if needsinfo:
...         return True
...     return False
... 
>>> timeit.timeit("test()", setup="from __main__ import test", number=1000000)
1.054154872894287
>>> timeit.timeit("test2()", setup="from __main__ import test2", number=1000000)
1.5020270347595215
```

Using an iterator instead of a generator.

`test2` is a traditional generator expression. It computes the full list according to a criteria, while `test` creates an iterator expression, that gets executed until the first match only when called by a `next()`. Each subsequent call executes a new iteration, until the end where there is no match anymore.

You can see that with 

```python
>>> needsinfo = (label for label in labels if label.startswith('status-needsinfo'))
>>> next(needsinfo)
'status-needsinfo'
>>> next(needsinfo)
'status-needsinfo-karcow'
>>> next(needsinfo)
'status-needsinfo-and-guacamole'
>>> next(needsinfo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

so instead of testing if we have a list, we test if we have a result at the first iteration of the iterator and we return.

**Comment by laghee** [comment]
Re-installing the requirements (or installing them finally, who knows) fixed my testing issues.

And Python is fun -- thanks, @karlcow! On it!
