### ISSUE TITLE
Add "browser-focus-geckoview" to EXTRA_LABELS allowlist

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2537]
Right now we can't distinguish between Focus GeckoView and Fennec, because they send the same UA string. 

As a stopgap solution -- if we encounter a bug w/ firefox-focus and firefox-mobile, we'll know it's a GeckoView bug.

**Comment by karlcow** [comment]
The fact we can't detect is a good thing (aka user agent sniffing doom world). 

`browser-focus-geckoview` doesn't seem to be a good path, because it goes against our attempt for simplifying the labels.
If we think there will be two `browser-focus` type then maybe we need to have a 
`render-blink`, `render-gecko`, etc.

About detectability I remember in the past a discussion where another mozilla team wanted to add fingerprinting through the UA, and Gervase suggested to have this information accessible only to a specific client with priviledged access. Basically the identification would be not visible from the Web except if it's webcompat.com, which means modifying Gecko.

**Comment by miketaylr** [comment]
https://github.com/mozilla-mobile/focus-android/pull/2845 landed today sending `browser-focus-geckoview`, but we can easily send in a PR to amend it. I think we should whitelist this in the short term, and send in something better thought out soon after (around the time we re-organize all the labels).

> If we think there will be two browser-focus type

I guess just `browser-focus` and `browser-focus-geckoview`.

> Basically the identification would be not visible from the Web except if it's webcompat.com, which means modifying Gecko.

As is, there's no way to detect. But it seems we only expose the report site issue menu item for geckoview, so that's good enough. Anything that doesn't have `browser-focus-geckoview` will be webview.

**Comment by karlcow** [comment]
Putting this here to remember what it does. 

<img width="311" alt="capture d ecran 2018-07-10 a 11 03 16" src="https://user-images.githubusercontent.com/505230/42485080-fa5da2a2-8430-11e8-8fab-02bdad959da6.png">
