### ISSUE TITLE
The bug title is not reflected in GitHub

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2646]
**Environment:**
Browser / Version: Chrome 69 (Desktop), Firefox Nightly 64.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to https://webcompat.com/issues/19567
2. Observe the title (moviesanywhere.com - Login will not work).
3. Press g on your keyboard to be taken to the GitHub view of the issue.
3. Observe the title.

**Expected Behavior:**
The title is the same as on Webcompat.com (moviesanywhere.com - Login will not work).

**Actual Behavior:**
The title is generic (moviesanywhere.com - site is not usable).

**Notes:**
1. Screen capture attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/46669361-db276780-cbd7-11e8-836d-7dc3a941347f.png)

**Comment by softvision-sergiulogigan** [comment]
This is related to #1828

**Comment by karlcow** [comment]
@softvision-sergiulogigan yup it's kind of normal. 
On Webcompat.com, on the client side, we take a part of the title from GitHub (domain) and part of the description… which can be very long. So we cut it sometimes in the middle of a sentence. The important part is that it has no consequences on the original data quality. 

I'm hesitant to adjust the title on Github, because not all strings will be necessary as good as the one you got here. Maybe once we fixed #2629, we can see if the data quality has improved and think about changing that by directly pushing the data to GitHub. 

So I'm putting this on the backlog. Closing it for now.
