### ISSUE TITLE
Reduce the size of HTML sent over network

### ISSUE THREAD

**Issue by Anushi1998** [webcompat/webcompat.com#2679]
Minifying HTML can improve the network cost while loading a webpage and hence performance improvements! :-)

**Comment by miketaylr** [comment]
@Anushi1998 interesting idea. :)

I would love to see if we can measure any potential benefits before merging this.

In theory, it could help -- and if it's significant we should consider it. But it can also make debugging the site harder (even if the source files don't change, inspecting the page with devtools will make our jobs harder).

Another option is to do this only for the production site, if we have data that it's a useful optimization.

**Comment by Anushi1998** [comment]
Page | Minified HTML | Uncompressed | % increase
:---  | :---:  | :---:  | :--:
/(index) | 47.9 | 50.6 | 5.64
/(index logged in) | 48.2 | 51 | 5.81
/issues | 42.8 | 44.3 | 3.5
/issues/new | 43.6 | 45.7 | 4.82
/me | 43.7 | 44.9 | 2.75
/privacy | 40.5 | 42.1 | 3.95
/contact | 39.5 | 40.8 | 3.29
/contributors | 51.1 | 56.4 | 10.37
/contributors/report-bug | 45.8 | 48.5 | 5.9
/contributors/reproduce-bug | 43.4 | 46 | 5.99
/contributors/diagnose-bug | 41.4 | 43.5 | 5.07
/contributors/site-outreach | 47.9 | 51.6 | 7.72
/contributors/build-tools | 40.3 | 42.2 | 4.71
/contributors/web-platform-research | 41.2 | 43.2 | 4.85
/contributors/organize-webcompat-events | 42.5 | 45 | 5.88
/tools/cssfixme | 0.859 | 0.859 | 0

**Comment by Anushi1998** [comment]
@miketaylr I have measured the file size improvements we can get using minifying HTML. I think after minifying JS and CSS code we can acheive a better result.
I think the option will be better to consider for production purpose so that atleast we are ease at while debugging local site.

**Comment by karlcow** [comment]
@Anushi1998 In this case we need to balance the benefits and hurdles it might create.

The size will certainly be different, because it's the goal of minifying :) I guess what @miketaylr was hitting at with 

> I would love to see if we can measure any potential benefits

is measured **speed** improvements, taken into accounts other latency parameters.
For example if it improves the Time to interaction such as 0.5s on 10s, it's not that much of a gain.

And if you include caching comparison with cold start, it reduces a bit more the gain depending on the resources, specifically in the context of https://github.com/webcompat/webcompat.com/wiki/Architecture :)

**Comment by miketaylr** [comment]
> is measured **speed** improvements

Yes, sorry for not being more clear. The goals is measurable performance improvements, for example, does the page load faster.

**Comment by miketaylr** [comment]
I think probably it's not worth the efforts to implement this.
