### ISSUE TITLE
Error message is missing from the "Type of bug" section

### ISSUE THREAD

**Issue by cipriansv** [webcompat/webcompat.com#2725]
**Steps to reproduce:**
1. Navigate to: https://staging.webcompat.com/issues/new
2. Start filling the required fields. 
3. Skip to select a radio button from the "Type of bug" section.
4. Fill in the rest of the fields.
5. Click the "Report" button.

**Expected Behavior:**
"A type of bug must be selected" error message must be displayed above/under the "Type of bug" section.

**Actual Behavior:**
Nothing happens. No error message is displayed.

**Notes:**
1. Screenshot attached.
2. The issue is also reproducible if the "Is this information correct" section is empty. 
   "A browser version/Operating system is needed" error message must be displayed above/below the section's text field.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

sv;

![image](https://user-images.githubusercontent.com/45160931/49588166-b7ca3000-f96e-11e8-8cd4-8e68b529a932.png)

**Comment by karlcow** [comment]
To solve this, there is a need for an event listener on Report buttons, when they are not active, and double check that the Type of bug has been selected. 

In fact, we should probably display the error messages on all fields only when someone is trying to click the report button and the fields are incomplete.

* [ ] Create tests for checking if error messages are displayed once we click the report button
* [ ] Remove the error message displayed when the field has not been completed
* [ ] Replace the asterisk by `(mandatory)` in black
* [ ] Display the error message in red only when someone try to click on Report and mandatory fields are empty

**Comment by ksy36** [comment]
@karlcow Should fields in "Is this information correct" section become mandatory as well? 
If this is the case we'll probably need to add labels for those fields (Browser version and Operating system).

**Comment by karlcow** [comment]
About 

>  Should fields in "Is this information correct" section become mandatory as well?

So far it has not been that much of an issue, the information sent by the browser is mostly correct. It is rare that people delete it AND more important probably many people have no idea what would be the correct way to enter these. I even wonder if they should be hidden in a kind of expert mode for people who needs to modify them because they know what they are doing. 

Maybe AB testing could help us to figure this out #2873

**Comment by ksy36** [comment]
Regarding `Remove the current behavior where the error message is displayed when the field has not been completed`:

There are certain checks being performed on the Site URL field, for example, to determine whether the string is a valid url. Here are the [test cases](https://github.com/webcompat/webcompat.com/blob/367a93a18e18a901e653e8cec84dd44ca84aaa2a/tests/functional/reporting-non-auth.js#L68) explaining the behavior.

So, when an invalid string has been typed in the URL field and we switch to another field, the error should still show up, correct @karlcow ? Since for a user it's good to see the error right away, before clicking on the submit button. 

Similarly with GitHub username (it's not required, but being checked if filled).

**Comment by karlcow** [comment]
> So, when an invalid string has been typed in the URL field and we switch to another field, the error should still show up, correct @karlcow ? Since for a user it's good to see the error right away, before clicking on the submit button.

yes. 
On the other hand, the error should not show anymore if one types something wrong, then delete and switches to another field.
