### ISSUE TITLE
Handle pagination when fetching labels from GitHub

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2726]
In troubleshooting issue #2482, it seems like the problem may not be in the regex, but rather in the fact that we're only fetching the first 100 labels in our API call.

**Comment by karlcow** [comment]
ah interesting. These are the list of calls that GitHub does to display an issue page.
Specifically note the last two ones:

<img width="1249" alt="capture d ecran 2018-12-07 a 07 45 58" src="https://user-images.githubusercontent.com/505230/49648547-2f8e6e00-f9f4-11e8-9574-1f57c7beaab4.png">

I think it happens when there is a hover on the sidebar. Two http requests are done. Specifically the last one  is a partial server-side rendering of the DOM for the labels.

https://github.com/webcompat/web-bugs/issues/10000/show_partial?partial=issues/sidebar/labels_menu_content

it sends back HTML including

```html
<form class="js-issue-sidebar-form" action="/webcompat/web-bugs/issues/10000?partial=issues%2Fsidebar%2Fshow%2Flabels" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="FYQKp3ldsN/C4Lm+cVBSRHNk11ru9DbmwUVCVCdp9l9rZf3oycHs9RVUyofcH5F8BRA3M0LlWR779roB7eBxJA==">
  <input type="hidden" name="issue[labels][]" value="">
  <div class="js-filterable-issue-labels" data-filterable-for="label-filter-field" data-filterable-type="substring">
    <div class="select-menu-item label-select-menu-item js-navigation-item  selected">
      <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path>
      </svg>
      <div class="select-menu-item-text">
        <input class="sr-only" type="checkbox" data-label-name="browser-firefox" aria-label="browser-firefox" value="90471196" name="issue[labels][]" checked="">
        <div class="float-left color mr-2" style="margin-top: 2px; background-color: #FF4E00"></div>
        <div>
          <svg class="octicon octicon-x ml-2" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path>
          </svg>
          <div data-name="90471196" class="css-truncate">
            <span class="name">browser-firefox</span>
          </div>
        </div>
      </div>
    </div>
    <div class="select-menu-item label-select-menu-item js-navigation-item  selected">
      <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path>
      </svg>
      <div class="select-menu-item-text">
        <input class="sr-only" type="checkbox" data-label-name="priority-critical" aria-label="priority-critical" value="637127491" name="issue[labels][]" checked="">
        <div class="float-left color mr-2" style="margin-top: 2px; background-color: #DD0055"></div>
        <div>
          <svg class="octicon octicon-x ml-2" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path>
          </svg>
          <div data-name="637127491" class="css-truncate">
            <span class="name">priority-critical</span>
          </div>
        </div>
      </div>
    </div>

<!-- cut content - series of labels … -->

  </div>
</form>
```

**Comment by karlcow** [comment]
To be more precise the template is created server side as soon as we hover on the labels general header or the gear. It sends a fetch Only if you are logged in.

**Comment by laghee** [comment]
Related and possibly patchable with the same type of fix -- #2450.

**Comment by marimeireles** [comment]
The fastest way to do this is probably using server-side.

**Comment by laghee** [comment]
Looks like the [requests library](http://docs.python-requests.org) might make this fairly painless. Working on a patch.

**Comment by karlcow** [comment]
So I was wondering if GraphQL API would give us more control on this. There are currently 145 labels. The current limit of the REST API is returning 100 items… and so does GraphQL API.

<img width="1022" alt="capture d ecran 2018-12-08 a 05 39 11" src="https://user-images.githubusercontent.com/505230/49685128-d6821100-faab-11e8-8d79-be66d84c4f44.png">

And if I request only 100. 

<img width="1024" alt="capture d ecran 2018-12-08 a 05 41 41" src="https://user-images.githubusercontent.com/505230/49685136-f74a6680-faab-11e8-991e-3a1baaabb213.png">

The only benefit of GraphQL is be more compact in terms of results. Though it is slighly more complicated to create queries, a complete different logic.

**Comment by karlcow** [comment]
I guess probably at a point we could create in a larger scheme of things, the future of the webcompat API would be to abstract some of the GraphQL call into specific uris.

https://webcompat.com/api/labels -> returns list of all labels. 
Note also that probably that us requesting all labels all the time might not be the best idea. This list is pretty stable and we probably need only to adjust it when we create/destroy one label from the list.

**Comment by karlcow** [comment]
Stealing my own comment on The current PR
https://github.com/webcompat/webcompat.com/pull/2784#issuecomment-458407014


```python
@api.route('/issues/labels')
@mockable_response
def get_repo_labels():
    """XHR endpoint to get all possible labels in a repo."""
    params = request.args.copy()
    path = 'repos/{0}/labels'.format(REPO_PATH)
    return api_request('get', path, params=params)
```

I propose we go with a local list of labels.

## local
We do not request milestones each time we use them because we consider them stable. We could perfectly through a CRON job (for example, once a day or once a hour), have a script creating a local JSON file with the list of all labels. The JSON is then local, cached, with the appropriate ETAGs, and can be requested by the JS to build the menu without having to make any requests to GitHub. Performance++

Possible issue:
Being unsettled because the labels are not sync on webcompat.com with what exist on GitHub. Though currently… we don't have the end of the list at all… so probably an improvement. 😛 


`issues/labels` will read a file and we can probably have a bit of application caching for this as well. 

I will close the current PR.

* [ ] create a script to fetch the full labels list
  * https://api.github.com/repos/webcompat/web-bugs/labels
  * This returns a json which looks like
```json
[
  {
    "id": 887136356,
    "node_id": "MDU6TGFiZWw4ODcxMzYzNTY=",
    "url": "https://api.github.com/repos/webcompat/web-bugs/labels/Pre-triage",
    "name": "Pre-triage",
    "color": "f6ff84",
    "default": false
  },
  {
    "id": 904761165,
    "node_id": "MDU6TGFiZWw5MDQ3NjExNjU=",
    "url": "https://api.github.com/repos/webcompat/web-bugs/labels/Re-triaged",
    "name": "Re-triaged",
    "color": "30c148",
    "default": false
  },
```
The HTTP headers contains
```
<https://api.github.com/repositories/17914657/labels?page=2>; rel="next", <https://api.github.com/repositories/17914657/labels?page=6>; rel="last"
``` 
This gives the pagination requests.

* [ ] store the data in a utf-8 text? document with one word per line or in a JSON, maybe the same format that the JS is expecting. To discuss
```
Pre-triage
Re-triaged
…
```
* [ ] create a cron which run this script every x minutes.
* [ ] create a function to convert to the data (if store in text)
* [ ] adjust the route to read the data from the file.
* [ ] check the notion of application python caching for avoiding to re-read the file on the filesystem if not necessary at each request.

@laghee 

1. do you still want to work on this?
2. if yes do you prefer to have a fresh issue about it?

Thanks.

**Comment by karlcow** [comment]
Let's close here and follow-up on #2830.
