### ISSUE TITLE
[v15.4.0] [broken release] MarkdownSanitizerMixin

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2757]
@miketaylr @marimeireles 

We are not out yet of the woods. :) #2727 is not completely over. :)
```
 ReferenceError: MarkdownSanitizerMixin is not defined[Learn More] issues.min.js:7:15902

    <anonymous> https://webcompat.com/js/dist/issues.min.js?3054c48ab8310c374912a235d2407e15:7 
```

**Comment by marimeireles** [comment]
I'm not being able to reproduce the error on my computer.
What did you do to get this @karlcow ?

**Comment by miketaylr** [comment]
I'm also not able to reproduce on master -- @karlcow do you recall which page you got this error from? Thanks.

**Comment by miketaylr** [comment]
> https://webcompat.com/js/dist/issues.min.js?3054c48ab8310c374912a235d2407e15

Based on that, I would guess you saw this on an issue page? I wonder if there was an incomplete file transfer, or something else wacky. issues.min.js is supposed to contain the missing mixin...

Oh wait, I think I see the bug here:

https://github.com/webcompat/webcompat.com/commit/3e2cb6e0187bc9741a97334e4410af9efc8e952c#diff-479be0e05b1599c3c773ecac55f5ea04

The necessary markdown client libs are added only for localhost in this commit (if you look at the diff for webcompat/templates/issue.html). So we need to add those files to the concat task for issues.js: https://github.com/webcompat/webcompat.com/blob/3e2cb6e0187bc9741a97334e4410af9efc8e952c/grunt-tasks/concat.js#L36-L47

While we're there, we could remove a stray the md-sanitizer script on the issue list page: https://github.com/webcompat/webcompat.com/blob/3e2cb6e0187bc9741a97334e4410af9efc8e952c/grunt-tasks/concat.js#L56

**Comment by karlcow** [comment]
@miketaylr @marimeireles 
This is not fixed. I deployed v15.5.0  on staging

I will let it broken as-is so you can see for yourself.
https://staging.webcompat.com/issues/1000

And this is working.
https://staging.webcompat.com/about

but are broken too, but for another reason it seems (I'm investigating this one). 
https://staging.webcompat.com/
https://staging.webcompat.com/issues/new

**Comment by karlcow** [comment]
Would that be it?
https://github.com/webcompat/webcompat.com/blob/870203d4d75d6bdb3e737db33e4f3eb627c18244/webcompat/static/js/lib/comments.js#L24-L27

**Comment by karlcow** [comment]
also in issues.js

**Comment by karlcow** [comment]
> but are broken too, but for another reason it seems (I'm investigating this one).
> https://staging.webcompat.com/
> https://staging.webcompat.com/issues/new

This part is solved.

**Comment by marimeireles** [comment]
>Would that be it?

Yeah, that's probably the problem again.
`comment.js` isn't generated by gruntfile, that's why that's happening.

**Comment by miketaylr** [comment]
This makes no sense to me.

https://github.com/webcompat/webcompat.com/blob/master/grunt-tasks/concat.js#L36-L52 contains the sanitizer file, and the comment.js file. And is allegedly generated as issues.min.js.
