### ISSUE TITLE
staging.webcompat.com is down

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2816]
Looks like staging.webcompat.com is not accessible from any browser/platform

Nightly Mobile - Chrome Mobile - Nightly Desktop - Chrome Desktop
![image](https://user-images.githubusercontent.com/16573771/53971100-db834a80-4104-11e9-9aea-613f694a5b2f.png)

**Comment by softvision-sergiulogigan** [comment]
@alex-mayorga said on IRC:
`The only settings I've intentionally flipped here are network.security.esni.enabled and network.trr.mode`

Looks like with these settings, the page is opened.

**Comment by miketaylr** [comment]
I can reproduce on Chrome Canary (on a new laptop, where I've likely never visited the site), and on Chrome Mobile: `ERR_CONNECTION_TIMED_OUT`. Firefox release too.

Not sure if useful: https://www.digitalocean.com/community/questions/how-to-debug-solve-a-err_connection_timed_out-error-when-this-error-happens-on-some-browsers-but-not-in-another

Working for me in my Firefox Nightly browsers though, probably because I've visited before?

> The only settings I've intentionally flipped here are network.security.esni.enabled and network.trr.mode

These 2 prefs related to:

https://blog.mozilla.org/security/2018/10/18/encrypted-sni-comes-to-firefox-nightly/
https://wiki.mozilla.org/Trusted_Recursive_Resolver

Chrome doesn't support encrypted SNI.

**Comment by miketaylr** [comment]
> Looks like with these settings, the page is opened.

I changed `esni.enabled` to 2 and enabled `network.trr.mode`, and it still doesn't load for me in Firefox release.

**Comment by miketaylr** [comment]
For fun I just restarted nginx... not sure it matters. 

@softvision-sergiulogigan if you visit https://staging.webcompat.com/ directly (with HTTPS) does it work now? It's working on Chrome and Firefox release for me, which maybe just means we never configured redirects correctly?

**Comment by miketaylr** [comment]
> It's working on Chrome and Firefox release for me, which maybe just means we never configured redirects correctly?

Or maybe it got changed, I don't remember.

I think that was the issue. I just updated the nginx config to 301 to https, and now it's working for me. Can you verify @softvision-sergiulogigan?

**Comment by softvision-sergiulogigan** [comment]
> if you visit https://staging.webcompat.com/ directly (with HTTPS) does it work now?

Success! It's alive!
Thanks, @miketaylr
