### ISSUE TITLE
Prevent user from specifying blank Browser and Device fields [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2976]
I believe this is how it is on live but let's prevent the rare scenario of someone clearing the device/browser fields and clicking confirm:
 
<img width="1104" alt="Screenshot 2019-10-11 at 16 53 32" src="https://user-images.githubusercontent.com/42435754/66666097-d6ace900-ec47-11e9-9117-899f930de3ce.png">

If the fields are empty we give them the "red cross" failed validation with an error of "Browser required" and "Device required".

A user can always (and should be able to) revert to the previous step and click "Yes" if they cleared the fields in error.

**Comment by bacharakis** [comment]
Assigned to @munteanu210

**Comment by munteanu210** [comment]
This issue was fixed in PR #2993.

The fields are required now, and the user cannot continue unless the fields are filled in. Here's what the user sees when these fields are empty: ![empty-fields](https://user-images.githubusercontent.com/1682059/67236339-effb2580-f3fd-11e9-8438-67d9cbcccacb.png)

If for some reason the user decides to delete the data from these fields, then changes his/her mind and hits "Yes" (as an answer to the question above), the user will proceed to the next step confirming the data.

At the same time, the data from these 2 input fields gets reset to the initial values in case the user changes his mind again, and wants to proceed with the information from the Browser and Device fields.
![fixes-2976](https://user-images.githubusercontent.com/1682059/67236633-829bc480-f3fe-11e9-96d2-2a50edd6336f.gif)
