### ISSUE TITLE
Unsupported format error message should be displayed above the “Upload screenshot”

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3049]
URL: https://staging.webcompat.com/issues/new 
Browser / Version: Firefox Nightly 71.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/issues/new
    2. Fill in the requires information until reaching “Upload screenshot” area.
    3. Drag and drop a valid image type on the “Upload screenshot” area (e.g jpg.)
    4. Drag and drop an invalid type of file over the valid image (e.g txt).
    5. Observe behavior.
       
**Expected Behavior:**
Error message is displayed above the “Upload screenshot” area.

**Actual Behavior:**
An error message is displayed on the valid image and it is hardly visible.

**Note**
    1. Screenshot attached.
    2. Also reproducible on Chrome 78.0.3904.70
	
Affected area:
```html
<small class="label-icon-message form-upload-error">Image must be one of the following: jpe, jpg, jpeg, png, gif, or bmp.</small>
```

![image](https://user-images.githubusercontent.com/12184325/67573825-e9dcb000-f741-11e9-8b5d-c8e1f8e3f49c.png)

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

sv;

**Comment by miketaylr** [comment]
This also reproduces on the current form, but I consider this a bug we should fix. 

![Screen Shot 2019-10-25 at 10 38 36 AM](https://user-images.githubusercontent.com/67283/67584664-c13dc180-f713-11e9-9ef3-ee7bebb44022.png)

Probably we should just remove the existing valid image before displaying the error message (since it's confusing to show a valid thing and an error at the same time anyways).
