### ISSUE TITLE
[World is on Fire] Have a contingency plan when web-bugs repo disappears.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3118]
There is right now an incident.  The web-bugs repo is gone.

<img width="1013" alt="webcompat-web-bugs-repo" src="https://user-images.githubusercontent.com/505230/71700023-bd11dc80-2e05-11ea-8bd8-797032625f81.png">

We need a contingency plan and tools.

1. Missing a web page saying that the site is down currently.
2. Having a warning as early as possible on https://twitter.com/webcompat
    Ex: https://twitter.com/webcompat/status/1212880610089299968 
3. Have a backup of everything (at least comments and issues) so we can send a static version instead of the nothingness we currently have. #2449 
4. Consolidate our accounts information

<img width="977" alt="Capture d’écran 2020-01-03 à 08 51 17" src="https://user-images.githubusercontent.com/505230/71700130-3d384200-2e06-11ea-9bad-b1a36a7cb7c1.png">

**Comment by karlcow** [comment]
As for the January 2020 incident.
* Detected by @ksy36 
* Reported by @miketaylr to GitHub and the internal mailing-list of Mozilla webcompat team
* Tweeted by @karlcow on webcompat account.

* 7:15am Only webcompat-bot issues are gone from the repo
* 8:33am The full repo is gone.

**Comment by miketaylr** [comment]
We could revive some of the code from https://github.com/webcompat/webcompat.com/issues/2733 for a landing "page is down" page.

**Comment by miketaylr** [comment]
I've sent some messages via LinkedIn (one to @clarkbw... hopefully GitHub @support can reverse this soon, and help us understand why it happened without any kind of heads up).

**Comment by karlcow** [comment]
When the form can't communicate with github web-bugs. 
At the end of the process for users this is what happens. Probably another issue to solve in case of non communications with GitHub.

<img width="831" alt="Capture d’écran 2020-01-03 à 10 23 32" src="https://user-images.githubusercontent.com/505230/71702519-3d8b0a00-2e13-11ea-86e0-143238fda01c.png">

**Comment by karlcow** [comment]
@miketaylr and I created an incident report with more details that we are updating once the details are coming in. 

@miketaylr also created a PR #3119 to have a landing page for the route /issues/new It was deployed today on staging and production.

**Comment by miketaylr** [comment]
OK, so @github un-suspended the web-bugs repo, but @webcompat-bot's reports are still hidden. I've proposed the following plan (only listing technical details, there will be some social things to fix too):

1. Remove the option for anonymous reporting from webcompat.com today (Friday, Jan 3, 2020). This will allow GitHub authenticated users to continue to report issues. Currently all reporting is disabled; we’re serving a “maintenance.html” page. 
2. Come up with a plan for moving towards a private-by-default anonymous reporting flow, with issues being made public once triaged. I don’t suspect this will be a ton of work (more than a few weeks), but the devil is always in the details.
3. Make changes to our application to link screenshots by default, rather than display them inline. 
4. Make changes to our application to prevent .onion URLs from being reported
5. Come up with a better plan for automated methods of tagging NSFW content long-term. 
6. Once we have a private-by-default anonymous reporting workflow in place, I will be in touch to request that the issues reported by @webcompat-bot be made public again. I've asked if we can audit the remaining issues to ensure all harmful content is deleted. 

This is the short-term plan. We will likely have a lot of discussions in Berlin about medium- to long-term plans about hosting choices, the GitHub platform, anonymous reporting, illegal content, etc.

**Comment by karlcow** [comment]
@miketaylr In complement to https://github.com/webcompat/webcompat.com/issues/3118#issuecomment-570677319, I created [Webcompat Belt On project](https://github.com/webcompat/webcompat.com/projects/7) and the [Remove illegal content](https://github.com/webcompat/webcompat.com/issues/3129) issue.

**Comment by karlcow** [comment]
@miketaylr should we close this one? As we set things in mmotion in the project itself.

**Comment by miketaylr** [comment]
I think it makes sense, yes.
