### ISSUE TITLE
Send the "moderation in process" message to the public issue

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3150]
@karlcow has a suggestion here: https://github.com/webcompat/webcompat.com/pull/3147#discussion_r365616901

It will return the text from #3137

**Comment by miketaylr** [comment]
This should happen somewhere in issues.py, https://github.com/webcompat/webcompat.com/blob/master/webcompat/issues.py#L26 is a good place to start.

@karlcow has suggestions for content in https://github.com/webcompat/webcompat.com/issues/3137 which are good. 

@ksy36 would you like to work on this?

**Comment by karlcow** [comment]
Repeating here the suggestion here:

https://github.com/webcompat/webcompat.com/blob/588b1d1c97eccf8423c834efc272aeacc080006e/webcompat/issues.py#L26-L32

This should probably be renamed:

```python
def moderation_template(status):
```

Though it's not even sure we need a specific function for this, because this is just calling one specific object, text.

https://github.com/webcompat/webcompat.com/blob/588b1d1c97eccf8423c834efc272aeacc080006e/webcompat/issues.py#L56
