### ISSUE TITLE
Ensure labeler webhook is configured for the private repo

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3155]
* [x] Adds milestone `accepted` on https://github.com/webcompat/web-bugs-private/milestones
* [x] Adds the webhooks labeler to https://github.com/webcompat/webcompat-tests-private
* [x] Adds the webhooks labeler to https://github.com/webcompat/web-bugs-private
* [x] Adds label `status-notacceptable` to https://github.com/webcompat/web-bugs

**Comment by karlcow** [comment]
@miketaylr Could you explain what is it about? 
Is it for the PATCH in #3140

**Comment by miketaylr** [comment]
>  _No description provided._

heh, sorry.

I mean the current `https://webcompat.com/webhooks/labeler` webhook that runs on web-bugs to add the new issue labels (browser, priority, etc).

https://github.com/webcompat/webcompat.com/blob/742d7c5a0bc1da562624c53feb282801cf38c29f/webcompat/webhooks/helpers.py#L171

My thinking is this would run for new private issues, and when we PATCH over to public, we copy the label state already applied.

(I guess we need to update this: https://github.com/webcompat/webcompat.com/blob/742d7c5a0bc1da562624c53feb282801cf38c29f/webcompat/webhooks/helpers.py#L192)

**Comment by miketaylr** [comment]
So to be more clear: remove it from web-bugs(-public) and add it to web-bugs-private.

**Comment by karlcow** [comment]
> So to be more clear: remove it from web-bugs(-public) and add it to web-bugs-private.

@miketaylr probably not a good idea ;) because auth'ed bugs go directly to web-bugs and are being labeled by the webhook. Also milestone assignment too. :)

**Comment by karlcow** [comment]
Also it means we have to recreate all the labels (~240) on the private repo. Do we really want to do that? 
Or is it because you are already going to phase 2 with triage in private (I would avoid jumping to phase 2 before Berlin). 

Another option, the public repo could also have the labels already assigned with the boilerplate in moderation. SO when moderated positively it is just about to PATCH the title and the body.

**Comment by miketaylr** [comment]
> @miketaylr probably not a good idea ;) because auth'ed bugs go directly to web-bugs and are being labeled by the webhook. Also milestone assignment too. :)

D'oh! Yah, forgot that. 🙈 

>  Or is it because you are already going to phase 2 with triage in private (I would avoid jumping to phase 2 before Berlin).

Nah, just trying to think through the plan. 

> Another option, the public repo could also have the labels already assigned with the boilerplate in moderation. SO when moderated positively it is just about to PATCH the title and the body.

That would work, I think.

> Also it means we have to recreate all the labels (~240) on the private repo. Do we really want to do that?

Hm. Not sure.

**Comment by karlcow** [comment]
1. We need to configure the private-repo to send POST to /webhooks/labeler (or eventually a separate route) (so adding the webhooks to the repo is good)
2. We need to make sure to **NOT REMOVE** webhook from public-repo (just stating it so it's 100% clear)
3. We need to adjust the logic of webhook so that the **metadata** (browser version, priority, etc.) received from the private repo are written on the public repo. 

Maybe something like this can work. This is just to help thinking and identifies the issue. 

![workflow](https://user-images.githubusercontent.com/505230/72403542-bab06a80-3795-11ea-99d7-c0885b6c101d.jpg)

**Comment by karlcow** [comment]
Some [musings around metadata](https://gist.github.com/karlcow/7f35ec564c8b8e30d340d88a615eb889) for the future. I'll add this to Berlin agenda. :)

**Comment by karlcow** [comment]
Ah there is another way to do it, which might be simpler than the [webhook in the previous comment](https://github.com/webcompat/webcompat.com/issues/3155#issuecomment-574483987).

Instead of having the webhook listening to the private repo we can directly use the form data and `report_public_issue` to assign the right metadata.

https://github.com/webcompat/webcompat.com/blob/742d7c5a0bc1da562624c53feb282801cf38c29f/webcompat/issues.py#L54-L60

**Comment by karlcow** [comment]
These configurations are in place.
