### ISSUE TITLE
The <acceptable use> link redirects to a 404 page

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#3186]
After logging an issue, the page that the user gets is the bug shell - "In moderation queue".
The <acceptable use> link redirects to a 404 page.
https://webcompat.com/terms#acceptable-use

![image](https://user-images.githubusercontent.com/16573771/74011251-04a10080-4990-11ea-9358-874501dbf94c.png)

**Comment by softvision-sergiulogigan** [comment]
Also
![image](https://user-images.githubusercontent.com/16573771/74012336-b17c7d00-4992-11ea-95a0-5411a5dafe23.png)

**Comment by ksy36** [comment]
I think this https://github.com/webcompat/webcompat.com/pull/3168  hasn't been deployed on production yet

**Comment by karlcow** [comment]
the route exists

https://github.com/webcompat/webcompat.com/blob/94911bcce14261dcc8a18a61fc9fcc725716dfd2/webcompat/views.py#L440-L446
Added by https://github.com/webcompat/webcompat.com/pull/3168/files

this is  deployed already on staging.

**but** as @ksy36 this is not yet in production

https://webcompat.com/terms#acceptable-use vs https://staging.webcompat.com/terms#acceptable-use

and we are forced to use a fully qualified domain name because of github.
