### ISSUE TITLE
Fix 2 issue template regressions

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3311]
I forgot to do this, so right now the timestamps are long!

(I made one of these for the issue page already, so probably very simple to import and re-use).

**Comment by ksy36** [comment]
I've noticed a small bug related to the same template, when going to a url with comment anchor (e.g. http://localhost:5000/issues/1784#issuecomment-632360709) a error is thrown, since the element with id `issuecomment-632360709` does not exist

Adding `id="issuecomment-{{ response.id }}"` to this element fixes it
```html
<div class="issue-comment js-Issue-comment grid-cell x2">
```
Could you please add it since it's in the same template? 🙏

**Comment by miketaylr** [comment]
Whoops, thanks for noticing. :)
