### ISSUE TITLE
Create module for rendering issues with comments as a static HTML file

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3326]
It should be possible to create a method that takes an issue number as an argument and produces an entire issue page as static HTML.

**Comment by karlcow** [comment]
Thinking of which form it could take. 
Probably related: https://github.com/karlcow/webcompat.com/commit/c76efa24da3604fb8bddddf50e1e37e576d980e6

```python
def freeze_issue(issue_number):
    """Fetch an issue and its comments.

    it should return a dictionary with 
    - issue_data: dictionary of useful information 
    - comments: list of dictionaries of each individual comments
    - freeze_date: date the request has been made.
    """
    pass
    return frozen_issue


def create_html(frozen_issue, template_reference):
    """Make an html version of the frozen issue.

    template_reference makes it possible to output different 
    renderings of the issue
    
    returns a string.
    """
    pass
    return issue_as_html
```

**Comment by karlcow** [comment]
@miketaylr a couple of questions with regards to this.

1. what is the goal, aka in which workflow this will be needed?
2. "outside of flask context", should it be considered as a scripting tool?

I understand this is to keep a frozen version of an issue so it can be accessed later on. I'm trying to figure out how this should be done and where. 

but I can probably start with tests.

**Comment by karlcow** [comment]
Ah forgotten. When you say issue do you mean issue + associated comments?

**Comment by karlcow** [comment]
I discovered that it's part of the project. 
https://github.com/webcompat/webcompat.com/projects/10#card-39187506

I need to double check what were the expectations when doing comments.

**Comment by karlcow** [comment]
for what you did in the comments, you stayed inside the flask context. It's why I guess I'm confused.

**Comment by miketaylr** [comment]
Hi @karlcow, sorry for the confusing. It's possible my language is not precise here (surprise!).

> what is the goal, aka in which workflow this will be needed?

I think you already know, but to be clear: this will be used by whatever system we invent that archives a page as a static resource. I imagined some kind of program that listens to a webhook (for example, when an issue is locked) and generates a static copy of the issue then moves that to somewhere on disk (or wherever) to be served by nginx or flask later.

> "outside of flask context", should it be considered as a scripting tool?

It could be, or it could live inside the application as a module that archives an issue in response to a webhook. I could also see an external-to-flask queue solution like RabbitMQ handling those issues, and I think those would be treated like a scripting solutions.  I think I'll leave that up to you to decide what you think is the best in terms of architecture. ❤️ 

> I need to double check what were the expectations when doing comments.

I think ideally we archive all the comments as well. But we can take shortcuts here. For example, if an issue has more than 100 comments, we could have a "load more comments" UI. But then we still have a dependency on GitHub services. Ideally if we had more than 100 comments, we would just fetch the next page, etc.

**Comment by karlcow** [comment]
@miketaylr thanks for the answers. It clarifies. 

I may update this below later.

# Thinking out loud mode

* in `static/issues/`, we could have the statically generated html files. `/issues/1234` would request the file located at `static/issues/1234.html`
* **criteria** for archiving: Once the issue is **locked**, the issue is considered static. 
* **signals**: 
    - The `issue.json` has the parameter `"locked": true,`.
    - webhook event on issues has an `"action": "locked"`
* These two signals create two opportunities, not necessary exclusive.

So we could imagine this in different ways:

1. Let `A` be a random HTTP request (natural traffic) to an issue `/issues/nnnn`
2. `views.py` 
    - checks if `/static/issues/nnnn` exists
        - yes, it serves it, aka html.
        - no, it fetches it from GitHub through the webcompat API.
    - on receiving the json, 
        - it can generate the usual response
        - check the value of `locked:`, if `true`, create a signal for a to_be_frozen queue
3. The to_be_frozen queue generates  static version of the page in `/static/issues/nnnn` so the next person get the frozen version.
4. An issue can be locked and unlocked by admins. It's happening very rarely, but has happened. Also project collaborators can comment. It means that things can change after locking. So probably we need another signal based on the date of the last time it was updated. 

## benefits

* if we scrapped all the static files by mistake or by choice, it can be easily regenerated. 
* Natural traffic drive the priority
* BUT if we want to generate the full static view, it's just a matter of having a bot requesting all the pages. 

## status change/updates
* the webhook event for `"action": "unlocked"` could be monitored to **remove** a static file or add it to a regeneration queue.

## static html content

* The creation date and last updated date (and/or archived date) should probably be visible.
* The design of the archived issue, doesn't have to be exactly the same than the live issue, maybe it would even be a benefit to make them different.

**Comment by karlcow** [comment]
Note that the system of generating on the fly could be used to  generate a on the fly archive of all issues even the ones which are not locked a kind of static cache, with the help of webhook events. 
For each event, we regenerate the static html of the issue attached to this event, outside of what Flask is doing. The danger being too many actions on the same files, when a lot of events are done. Maybe to select what we want to trigger on or if we accept a slight delay in terms of freshness. The freshness could be brought through JS too. instead of rewriting an empty templates it would rewrite a fully written html issue based on the last updated date.

**Comment by karlcow** [comment]
@miketaylr do you have an opinion on 

> The design of the archived issue, doesn't have to be exactly the same than the live issue, maybe it would even be a benefit to make them different

And what should be the characterics of the navigation of this page. Same colors? Navigation back to home, but no need for the rest? or full design, which can be slightly more challenging with the current architecture and the desire to not duplicate too many things.

**Comment by miketaylr** [comment]
@karlcow by navigation, are you referring to the navbar in the current site? Or something related/different?

I think it's a good idea to have a slightly different design. It should probably be obvious that the issue is archived. "Home" and "Report a Bug" seem like the most useful content to have in the header, the rest isn't really necessary.

I like how GitHub does this visually:

![Screen Shot 2020-07-30 at 11 49 44 AM](https://user-images.githubusercontent.com/67283/88950823-cc052400-d25a-11ea-975d-85fe9fc1ed27.png)

**Comment by miketaylr** [comment]
As for labels and milestone, those could be simple HTML markup, there's no need for any of the interactive bits to be included in the page.

**Comment by karlcow** [comment]
> It should probably be obvious that the issue is archived.

done. https://github.com/karlcow/webcompat.com/commit/4bcdc92329f89d3f79f43dcc0a8135a027c19a35
