### ISSUE TITLE
Some issues with empty <!-- @reported_with: -->

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3360]
https://github.com/webcompat/web-bugs/issues/52582 is one example:

![Screen Shot 2020-06-24 at 10 54 18 AM](https://user-images.githubusercontent.com/67283/85589310-13b7e080-b609-11ea-8920-dcc5b648924b.png)

I would have expected this to be impossible, since there should be a fallback if there's no `src` param. Perhaps we need to add one to the Fenix/AC web extension?

**Comment by karlcow** [comment]
related to #3359

**Comment by karlcow** [comment]
to get what is happening if someone does report an issue with `src=''`

**Comment by karlcow** [comment]
> I would have expected this to be impossible, since there should be a fallback if there's no `src` param. 

I'm not sure that's entirely true.  what is this doing and when?

https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/form.py#L297

for example if `src=''` they key exists, and you do not get `web`, but the empty value which would indeed creates the results in your first comment. It's why I opened #3359 so that we have a validation mechanism on what comes in and have probably a more explicit message if something is missing.

**Comment by miketaylr** [comment]
Good point, sending src=`` is odd but possible I guess.
