### ISSUE TITLE
Add a link to the github issue that will point to the generator page

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3374]
Once an issue was moved to "needscontact" it would be nice to add a comment to the issue with a link to the generated outreach template, e.g. https://webcompat-outreach.herokuapp.com/issue/33213

**Comment by karlcow** [comment]
@ksy36 Maybe we can create a new route here. something along https://webcompat.com/outreach/33213 with either a redirection, aka Location or a Content-Location HTTP header. In case the webcompat-outreach.herokuapp.com domain is sunset or modified one day, it gives more flexibility on our side to control the redirections, instead of having users ending up with a legacy redirection going to a 4** code.
