### ISSUE TITLE
Cache busting hash broken

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3401]
This happened between versions 34 and 35:`<script type="module" src="/dist/ga.js?missing_file"></script>`

**Comment by miketaylr** [comment]
![Screen Shot 2020-07-17 at 3 10 32 PM](https://user-images.githubusercontent.com/67283/87827071-ada52e80-c83f-11ea-99be-b19001c014c5.png)

**Comment by miketaylr** [comment]
Maybe related to https://github.com/webcompat/webcompat.com/pull/3390/files#diff-bf19058f770313b72ea047161f30e968R40-R42?

**Comment by karlcow** [comment]
@miketaylr before accepting this #3402 PR I need to understand what is happening in "Cache busting hash broken #3401 "

1. The code ends up with `missing_file` instead of the hash.
2. `missing_file` is added when the file can't be found. 
3. staging is currently with https://staging.webcompat.com/.well-known/deployed-version `61370ccc225b6a55582513ae06ad4c441980159b`
4. production is currently with https://webcompat.com/.well-known/deployed-version `8656f17526d3b64c367ea4f2bbb742a2b388c937`
5. They both have hashes and localhost doesn't have hash. Or maybe is it because it's not deployed yet?

**Comment by karlcow** [comment]
ok understood. See my comment in https://github.com/webcompat/webcompat.com/pull/3402#pullrequestreview-451243795, the issue was with the leading `/` is [os.path.join](https://docs.python.org/3/library/os.path.html#os.path.join). Using `os.path.join('/root/blah', '/somewhere/booh')` instead of `os.path.join('/root/blah', 'somewhere/booh')`

**Comment by miketaylr** [comment]
Thanks for the review and suggestions @karlcow. I'll get to those this afternoon.

**Comment by miketaylr** [comment]
> They both have hashes and localhost doesn't have hash. Or maybe is it because it's not deployed yet?

(just to clarify, localhost (aka master) has the broken no-hashes state. production has the pre-`missing_file` version. staging has the mike's PR in #3402 proposed fix)

**Comment by karlcow** [comment]
So thanks for doing this. #3407 

This will require a bit more explanation. I think I know why this is happening. It's about scope of variables in the case of decorators which are just nested functions. I will put it down in writing tonight if I have finished what I have to do first for today, so we do not repeat the same mistake later. 

That was an interesting unboxing: issue inside an issue inside an issue 🥡
