### ISSUE TITLE
problems submitting ticket with FF nightly on android

### ISSUE THREAD

**Issue by scheinercc** [webcompat/webcompat.com#3493]
The Url got filled automatically, but hitting the "confirm" button doesn't do anything.
https://webcompat.com/issues/new

Nightly 201007 17:09 (Build #2015768331)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0

**Comment by miketaylr** [comment]
@scheinercc can you give some more detailed steps to reproduce?

On my pixel 3, with the latest Nightly, if I go to twitter.com and click "Report Site Issue" (from the Addons menu), the URL is auto-filled for me, but then it auto-scrolls to the next step (which I believe is expected behavior if you come from the addon).

**Comment by scheinercc** [comment]
@miketaylr thanks for checking! It works for me now the way you described it. The latest nightly fixed a few other things as well, so I guess it might have been that version only.
