### ISSUE TITLE
search is broken

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#3639]
I'm unable to search anything in webcompat.com every times I get this error ![image](https://user-images.githubusercontent.com/1997108/140665410-f8fa91b9-47d5-4449-a10c-e8d58317c5c4.png)

**Comment by noreplyblitzline** [comment]
@magsout that means you are not the owner of whatever you're trying to access i would exit.

**Comment by karlcow** [comment]
🤔 So on Firefox Nightly Fresh Profile, no addons.
I get with the search in the homepage

![Capture d’écran 2021-11-08 à 09 24 23](https://user-images.githubusercontent.com/505230/140667839-e8f4a9dd-7fb9-4a82-914a-2d1b47b14618.png)

Then this is the results I got from the All issues page.

![Capture d’écran 2021-11-08 à 09 26 04](https://user-images.githubusercontent.com/505230/140667877-36b2c818-7eb4-40ba-bfb3-23e538cac7d7.png)


OK this is happening only when logged in.

This is working:

https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=doctolib%20is%3Aissue

Changing `&q=doctolib` by `&q=doctolib%20is%3Aissue` fixes it.

It needs to be adjusted.
https://github.com/webcompat/webcompat.com/blob/030c2613d9842379557e74aa6f16c2e59dac2e2f/webcompat/static/js/lib/issue-list.js

Also it means that all the Auth tests are "not testing the right thing anymore" in the sense that they are in a scenario which is not the same. Probably tests need to be fixed in a separate bug.

**Comment by karlcow** [comment]
This is a regression from #3629

**Comment by ksy36** [comment]
Thanks @magsout :) 
Found this https://docs.github.com/en/rest/reference/search#search-issues-and-pull-requests:

> Note: For user-to-server GitHub App requests, you can't retrieve a combination of issues and pull requests in a single query. Requests that don't include the is:issue or is:pull-request qualifier will receive an HTTP 422 Unprocessable Entity response. To get results for both issues and pull requests, you must send separate queries for issues and pull requests. For more information about the is qualifier, see "Searching only issues or pull requests."

Will add this parameter in https://github.com/webcompat/webcompat.com/pull/3641
