### ISSUE TITLE
Alexa sunset. Priority rethinking.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3656]
On May 1st, 2022, Amazon will sunset Alexa.
https://support.alexa.com/hc/en-us/articles/4410503838999

The priority flag for our bug is defined according to Alexa ranking. We need to rethink this strategy.

**Comment by karlcow** [comment]
Would be worth to add this to [2022H1](https://github.com/mozilla/webcompat-team-okrs/projects/15)

**Comment by ksy36** [comment]
One thing to add, since we'll need to rethink this, wonder if it makes sense to change the priority importance to priority importance per country (it could be a different label too). This could help us prioritize diagnosis.

Two examples:
 https://github.com/webcompat/web-bugs/issues/97492 has `priority-normal` label, but it is a [41 top site in Korea](https://www.alexa.com/siteinfo/auction.co.kr). So it's `priority-critical` for Korea.
https://github.com/webcompat/web-bugs/issues/83322 has `priority-normal`,  [#674 in US and #846 in Canada](https://www.alexa.com/siteinfo/theatlantic.com). So it's likely `priority-important` for these 2 countries.

**Comment by karlcow** [comment]
Yes it's a good opportunity to revise and improve the script here, which was trying to play with locales too. 
https://github.com/webcompat/webcompat.com/blob/408d8032dcdcdd94893b2ca84e071c9b71ba7926/tools/topsites.py#L131-L143

**Comment by ksy36** [comment]
Thanks for the suggestion, Mike :)

I've looked at 2 Tranco lists (with and without Alexa) and going to document my findings here. There are two things I've noticed so far that are worth considering when making the switch to Tranco. 

Also keeping  in mind this rule in https://github.com/webcompat/webcompat.com/issues/1533#issuecomment-299429187 from @MDTsai :

>  Critical: alexa top 100 in worldwide
    Important: alexa top 101-1000 in worldwide or alexa top 100 in tier 1 countries/regions
    Normal: alexa top 1001-10000 or alexa top 101-1000 in tier 1 countries/regions
    Others: others


**1) Ranking per country**
Tranco doesn't seem to have a mechanism to get top domains per country. So it may be worth preserving the Alexa's per country data that we currently have and not updating it when we make the switch (...and fetching the updates one last time before Alexa is deprecated). This would only apply to domains that have non-empty `country_code`:

<img width="784" alt="Screen Shot 2022-03-21 at 3 10 44 PM" src="https://user-images.githubusercontent.com/1303908/159346792-17429751-8777-457e-ba93-c218445f96e3.png">


Countries list that we fetch ranking for: 'US', 'FR', 'IN', 'DE', 'TW', 'ID', 'HK', 'SG', 'PL', 'GB', 'RU'. 

It's worth mentioning, there is a checkbox "Only include domains included in the Chrome User Experience Report of February 2022" on https://tranco-list.eu/configure, which allows filter by country. It doesn't seem to be accurate though - it's weighted towards global sites rather than local.

<img width="1216" alt="Screen Shot 2022-03-21 at 2 28 56 PM" src="https://user-images.githubusercontent.com/1303908/159340240-a87d22e4-f835-4833-90d3-b15f83db7ccf.png">



**2) For some sites ranking is lower than current Alexa's ranking and "perceived" ranking**

For certain sites, the ranking is lower on the global level (especially in the list without Alexa).

<img width="620" alt="Screen Shot 2022-03-21 at 3 36 46 PM" src="https://user-images.githubusercontent.com/1303908/159350546-d934ba4a-a446-4c9d-afd6-d1d5f0eba32c.png">

This matters once a site is out of the top 100 / top 1000. In this screenshot, in the Tranco list without Alexa all the sites that are considered to be in Alexa top 100, are ranked lower. In the Tranco list with Alexa some are still in the top 100 and etsy.com is out. 
Not sure how big of a concern this would be going forward. If Tranco is keeping Alexa's data for some time, then it's probably fine. We could also change the rule a bit to make sites that are in 150-200 Tranco rank be `priority-critical` (instead of the current 100).

Also just saw a message on Tranco's website (so my observations may not be relevant soon 🙂 ):

> We plan to continue maintaining Tranco, even after the deprecation of the Alexa ranking on 1 May. We are currently working on the next steps, including adding new data sources. We will announce more details in due time.

**Comment by ksy36** [comment]
An update here:

I've looked at https://pypi.org/project/tranco/ and it seems to be downloading a csv with 1 million domains, which seems a bit too much as we only need 10000. 

So I wrote a script that fetches tranco's API and gets a recent list by date, (for example https://tranco-list.eu/api/lists/date/2022-03-26) and then downloading a csv with 10k (https://tranco-list.eu/download/GZ6NK/10000).

As for storing it, I'm thinking to create 2 tables, one would contain data from this csv (domain and ranking) and the second one would contain top domains per country from Alexa (domain, ranking, country). There is probably no need to store priority, as it can be determined in the code, as it primarily depends on the rank. 

So the ranking would be determined as follows (will have to join two tables to get the rank):

- if domain only exists in the main table, use ranking from the main table
- if domain exists in both tables, use ranking from the second table (if the ranking per country is more important in the global table)

Thinking of going 2 tables route because when fetching updates from Tranco it would be easy to archive the old table and just create a new one (in the same it's done right now) without the need to search and update a rank for each domain. And the per country rank table will not be updated once Alexa turns off their API. Regions that we're fetching at the moment: 'US', 'FR', 'IN', 'DE', 'TW', 'ID', 'HK', 'SG', 'PL', 'GB', 'RU'.

I'm probably missing something, so any insight or correction is appreciated :)
