### ISSUE TITLE
Communication strategy

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#455]
As discussed in the retro (https://github.com/webcompat/webcompat.com/wiki/Retro-from-December-2014-work-week/), we need to consider a communication strategy for:
- getting the word out to potential bug reporters and developers 
- finding more contributors to the project 
- gaining more support from all the browser vendors

Could include blog posts, Twitter, conferences, Webcompat summit, workshops, talks, etc, etc

**Comment by hallvors** [comment]
We have a reach of 500 followers on MozWebCompat Twitter account and 300 on the Webcompat Twitter account. We should aim to use Twitter every second day or so to tweet a question like "Someone knows a contact at Company X who could look into ..." or "Is someone using bank X and can check if this is a problem? ... "

We should have a higher profile inside Mozilla itself (more project meeting updates) because many can help us without spending much time, i.e. if you just know the right way to contact a certain person and let us know..

We should have more (and better maintained) tasks on oneanddone.mozilla.org

If we can go to conferences and give talks, that is great. But webcompat may not be a "sexy" topic..

**Comment by hallvors** [comment]
@karlcow how exactly should we achieve the "tweets every couple of days" practise? I'm doing random  triage on webcompat.com and can tweet about issues - but you should feel free to do so too..

**Comment by miketaylr** [comment]
This is covered by the work that Ola is proposing.
