### ISSUE TITLE
Improve labels

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#522]
var css / JavaScrript / HTML

**Comment by miketaylr** [comment]
For removing the current border color, we just need to remove the inline `border-color` style from https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/issue-list.html#L78.

In #482 we decided to ditch the color and go with a gray border/underline instead: https://github.com/webcompat/webcompat.com/issues/482#issuecomment-68553044

**Comment by magsout** [comment]
- style
- name
- color

**Comment by miketaylr** [comment]
Ah, we also need to figure out what to do with the label backgrounds as displayed on an issue page, like https://webcompat.com/issues/222 for example.

**Comment by miketaylr** [comment]
All gray background labels might not be terrible.

**Comment by magsout** [comment]
@miketaylr 

> All gray background labels might not be terrible.

which labels ?

**Comment by karlcow** [comment]
Could @magsout explain what it means by "improve labels"? :)
Asking because we started to discuss it in https://github.com/webcompat/webcompat.com/issues/402#issuecomment-63270363 and then we open a #436 which I think we should really do. To make the UI of webcompat.com more useful and easier to use.

**Comment by magsout** [comment]
@karlcow We can consider it as a duplicate of these issues, so we can close
