### ISSUE TITLE
[testing] login to github will redirect to a different URI

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#537]
Step to reproduce.

With a clean profile (not logged to github, not logged to webcompat.com)

1. Starts your local instance `python run.py`
2. Start a clean profile browser
3. Enter `http://127.0.0.1:5000/`
4. click on login
5. The user is redirected to github Web site.
6. login/password. Enter
7. The user is redirected to `http://localhost:5000/`
8. fix code.
9. restart the server.
10. Reenter `http://127.0.0.1:5000/`
11. Try to login again.

It will not work a callback is happening. There's a 200 OK in the log but nothing else happened. The UI is not changed to logout and the avatar icon.

What I suspect is that `http://127.0.0.1:5000/` != `http://localhost:5000/`

Suggestions:
* Either having a way to redirect to the right localhost or 127.0.0.1 when started on one of these.
* Either having the starting message of `python run.py` be localhost.

**Comment by miketaylr** [comment]
We probably just need to document `localhost` instead of 127.0.0.1. GitHub requires us to put in the OAuth callback location "Authorization callback URL", which is set to http://localhost:5000/callback for our test application. But people could create their own test applications and use 127.0.0.1 if they want. It just needs to be consistent @ https://github.com/webcompat/webcompat.com/blob/master/config.py.example#L66 and in the application settings.

But maybe just telling people to use localhost is simplest. :)

**Comment by karlcow** [comment]
Yes probably.
