### ISSUE TITLE
Attempt validation on empty bug reports

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#613]
To prevent not-very-useful bug reports like webcompat.com/issues/1013, we should make sure there's actually something written. It would be hard to get perfect, but we can easily detect if the last bits of the textarea are just:

```
Expected Behavior:

Actual Behavior:
```

**Comment by tagawa** [comment]
On the other hand, a report with "layout is messed up" is better than no report, so ideally a gentle nudge - "fancy adding more details?" - rather than blocking submission might be better. Would require more code logic though.

**Comment by miketaylr** [comment]
Hmm, yeah. I like that idea better. The primary reason we added the "greatest hits select" options was to get at least *some* information from a report.

**Comment by miketaylr** [comment]
(We could probably just use our existing "flash" mechanism for this.)

**Comment by karlcow** [comment]
yes +1 to this. Let's add something along, "any details you add will help us diagnose."

**Comment by miketaylr** [comment]
To fix this bug we need to somehow detect empty (or nearly empty?) bug reports as people are trying to file them, and then sending a flash message to them along the lines of "fancy adding more details?" or "any details you add will help us diagnose". Not those exact words, but we can bikeshed that once the work is done. :smile: 

I think this should probably happen via the bugform.js validation, maybe when `descField` is `blur`red or on submit? We can send a client-side flash message, that way people don't have to wait for the page to reload.

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L92 shows how to trigger a flash message via JS.

We should probably only show the message once, and not block on it -- not a lot of details is better than frustrating people and not getting a report I think.

**Comment by karlcow** [comment]
Another way is to go through steps on the server python side.
Yes I know it goes again common beliefs. 

* POST to webcompat 
* render as a summary page of the bug report (aka preview) with detecting on the server side if it could be improved and sending appropriate messages for it
* The user can complete or finally submit.

I would avoid *flash* messages (I understand flash as something which appears and disappear). The issue here with the UX is that you know it's empty only when the user is pushing Submit. 

Associated to that make sure our forms are forms `form/input/button` and not `div`s ;)

**Comment by dshgna** [comment]
Hi @miketaylr @karlcow I'm interested in working on this issue. 

Just small idea from my side: What about having the form highlighted in red by __default__ till it contains something more than  "Expected Behavior:Actual Behavior:" and a prompt beneath it "any details you add will help us diagnose."

**Comment by karlcow** [comment]
I guess we start to have a good choice of options here. 
Maybe @calexity would know how to test our different options for the UX. Aka which one would be more likely to engage people doing the task.

Basically the why we want more details is that we want to be sure to be able to help the user.
And for this we need to be able to reproduce it and understands it. 

Or maybe we are trying to put more red lights on the road or constraints, when we should have a better UX.

@dshgna that would be great if you could help. I don't think we have totally nailed it yet. Maybe we should go with a prototype and put it on the staging server to see how it feels in both desktop and mobile environment.

^_^ /me needs to kick his butt on doing more reporting on mobile itself.

**Comment by dshgna** [comment]
To continue the conversation that @karlcow and I were having over IRC on possible design issues:

1. 'Expected behaviour' and 'Actual behaviour' are there as placeholders for 'Give more details', which may imply that it is a guideline rather than a 'very-good-to-provide' to have. Perhaps having two input fields for 'Expected behaviour' and 'Actual Behaviour' with some descriptive text like 'What should happen?' and 'What is happening' would prompt more interaction.

2. I personally was a bit confused by the 'steps to reproduce' in the  'Give more details' textarea. The form already lists the site URL. So I understood this as the steps to reproduce a specific instance such as opening a modal, or playing a video, etc.

**Comment by danguilherme** [comment]
How is this issue going? I think it's more of a UX problem than any other.

I completely agree with @dshgna's first point. Illustrating it, the interface could be instead of this:
![before](https://cloud.githubusercontent.com/assets/1488378/18071269/d8e65bb4-6e2a-11e6-81e6-87a2214c30fd.png)

...it could be something like this:
![after](https://cloud.githubusercontent.com/assets/1488378/18071852/3422b366-6e2f-11e6-9955-a105d4865d05.png)


---

The final result would be the same as we have today (a single, concatenated text of steps, expected and actual behaviors). With separated text areas we can better guide users through form completion.

Maybe make something like [Booking](booking.com)'s room rating form? (`the best recommendations have X or more characters.`, `you're almost there, aren't you missing any details?`, though I believe it's too much for this case.)

I put myself available to tackle this issue. Please remember this screenshot is supposed to be a draft :smile:.

**Comment by miketaylr** [comment]
> How is this issue going?

Nobody is working on it right now... so ummm 💀 😄 

> Maybe make something like Booking's room rating form?

Can you take a screenshot of that? The link isn't working (and I've never used booking... not sure where to look. :))

> I put myself available to tackle this issue.

That would be awesome!

**Comment by danguilherme** [comment]
It seems like I cannot post a recommendation without actually going to a booked hotel.

The behavior is:
- User opens the form
- A tip bellow the text area reads `The best recommendations have more than 120 characters`
- User starts typing
- As character count is increasing, other tips show up, like `It's getting good. Aren't you missing any detail?`, and so on

Again, I think this particular approach is just too much for this form, just wanted to mention this option.

---

As soon as we decide the approach, I can start doing something.

**Comment by miketaylr** [comment]
> Again, I think this particular approach is just too much for this form, just wanted to mention this option.

Ah yeah, that does sound like nice UX, but may be a bit much for a bug report (sometimes there isn't much to say and sometimes there's a LOT to say).

> As soon as we decide the approach, I can start doing something.

Let's try what you have in the proposed screenshot. We can tweak final wording once we have something working -- let me know if you need help knowing where to get started!

**Comment by danguilherme** [comment]
I'll check the contributing guides. If I need anything I'll let you know.

**Comment by danguilherme** [comment]
@miketaylr, after following the [contributing guide](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md), I still am not being able to run the server on my Windows machine. Is it necessary to install anything else? (It seems like the script is not ready to be run on Windows, as `source`, from bash, is used.)

Following is the terminal output after running `npm run start`:

```txt
$ npm run start

> webcompat@ start C:\Users\gventura\git\danguilherme\webcompat.com
> source env/bin/activate && python run.py

'source' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! webcompat@ start: `source env/bin/activate && python run.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webcompat@ start script 'source env/bin/activate && python run.py'.
npm ERR! This is most likely a problem with the webcompat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     source env/bin/activate && python run.py
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcompat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls webcompat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gventura\git\danguilherme\webcompat.com\npm-debug.log
```

**Comment by miketaylr** [comment]
Hey @danguilherme, yeah Windows compat for our build processes is apparently terrible. :(

There's probably better ways to do this, if you have experience we'd love contributions in this area!

**Comment by karlcow** [comment]
See the issue #1233 for the study about empty bug reports

**Comment by tagawa** [comment]
I'd say the Description field being required is enough. The more required fields there are, the higher the chance a reporter will give up. If they provide at least a description (together with the other basic info) that should be enough to look into an issue IMO.

**Comment by miketaylr** [comment]
I'm inclined to agree with @tagawa. Let's deploy the new form, and if we feel like we need more validation after getting some reports in, let's file a new bug. Thanks @cch5ng!
