### ISSUE TITLE
Design improvements for issue page (more compact?)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#617]
I think we could "tighten" up the issues page (for lack of a better term).

It feels unbalanced on desktop, maybe boxing in the original report as a comment like GitHub does would help?

The default status icon feels a little too big and the title can be a little unwieldy if its long.

![](https://cldup.com/Emy8aVmEcC-2000x2000.png)

Thoughts @karlcow @tagawa @magsout @calexity?

**Comment by miketaylr** [comment]
Seems related to #599.

**Comment by karlcow** [comment]
first step:

```css
.Issue-details, .Label-wrapper {margin-left: calc(59px + 0.8em);}
```

![issues screenshot](https://cloud.githubusercontent.com/assets/505230/7973869/9cc8deda-0a95-11e5-8f3b-db70ebd58778.jpg)

**Comment by calexity** [comment]
Agree @miketaylr and yes @karlcow that left margin fix helps.

I think we can 
- ditch the grey arrow (because we now have navigation or you can browser back)
- "Needs diagnosis" label and the title can both be smaller
- fix up comments
- fix overall alignment of the page

I can assign this issue to myself though I won't get to it for a couple weeks.

**Comment by miketaylr** [comment]
Thanks @calexity. :)~

**Comment by magsout** [comment]
Good idea for THE first comment. Tell me if you need help @calexity

**Comment by magsout** [comment]
Something like : 
![issue](https://cloud.githubusercontent.com/assets/1997108/8100037/8aaa7d50-1006-11e5-9b65-d1be69d5dd49.png)

**Comment by miketaylr** [comment]
Yesssss.

**Comment by miketaylr** [comment]
I think this is done!
