### ISSUE TITLE
Only update UI with label changes when successful.

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#671]

**Comment by miketaylr** [comment]
I don't even remember what this is about... :/

**Comment by magsout** [comment]
🤔

**Comment by karlcow** [comment]
ahah. :D  for not documenting :japanese_ogre: 

I think it's originated from something we had in the UI which was troubling.

Basically you were selecting the label on webcompat.com with the widget, then the list of labels would change, but this would be happening BEFORE the label had been changed on github side. The reason it was troubling is that if the label change didn't happen on github (for any reasons… intersideral failure of ze internet) the UI showed something which didn't happen AND at the next reload, the user is puzzled because the label is different again.

But I haven't had the issue for a long time. So I guess the rewriting of labels might have solved it somewhow. Let's close it and we will reopen if necessary.
