### ISSUE TITLE
[bug] new issues list is not correct

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#690]
1. Being logged on https://webcompat.com/
2. Go to All issues https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
3. Click on new issues https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new&sort=created&direction=desc

So far so good.
1. Ask for sorting as Oldest https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new&sort=created&direction=asc

The sorting includes contactready issues.

**Comment by hallvors** [comment]
I see these labels not excluded from the "New" category show up in the results, arguably these issues should appear:

* worksforme
* fixed
* duplicate
* needsinfo

(Apparently not all bugs with the three first labels are also *closed* - some clean up to do here?)

**Comment by miketaylr** [comment]
I think this bug is invalid now: following STR I end up w/ 

https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needstriage&sort=created&direction=asc

(Note, at the time "New" wasn't tied to a status label in the same way that status-needstriage is, and that's probably where the bug was).
