### ISSUE TITLE
[discussion] Simplify label/prefix handling with a proposed new LabelList model

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#783]
From IRC by @hallvors 

> I have a proposal, sort of: https://gist.github.com/hallvors/9cdf228aeb72598b78eb for a `LabelList` model initialized by either URL or array. Just `list.get('labels')` to get an array of objects fit to present in the page (`list[i].name` and `list[i].color` ready for your templates). just `list.save()` to send stuff to backend - prefixing should just happen. But it's not well tested yet :-p. Didn't really use the Vanilla.js framework ;). (when adding labels - when new things are checked, for example - it accepts `list.set('labels', listOfObjects)`). If you like that, I'll rewrite all code touching label stuff to use `LabelList`.

> @miketaylr said: "i'll leave some comments in the [gist](https://gist.github.com/hallvors/9cdf228aeb72598b78eb)"

**Comment by hallvors** [comment]
Thanks for reporting this issue on the suggested changes, @karlcow.
Early this afternoon I looked at this a little more and the new model seems to work well with a lot of the old code. The only thing I need to add now is code that will update the issue's labelList when you close the label editing dialog - will be interesting to see how/if that works. Hopefully this achieves a simpler and more maintainable label logic.

**Comment by miketaylr** [comment]
Can I ask what problem this solves over the current approach? Just thinking through this "outloud".

One benefit is that potentially we're not duplicating code, for example:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/labels.js#L13
https://github.com/webcompat/webcompat.com/blob/5ca92e76aa8eee5ec63eabe641ced19565eac07d/webcompat/static/js/lib/models/issue.js#L127

So I guess we're just merging all the label stuff into a single model? That sounds reasonable.

One place this will fail is clicking on a label in `/issues` to do a label search. We reply on a `labelsMap` property of the issue model:

https://github.com/webcompat/webcompat.com/blob/5ca92e76aa8eee5ec63eabe641ced19565eac07d/webcompat/static/js/lib/models/issue.js#L136
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/issue-list.html#L78

Granted, that could probably be improved as well.

**Comment by hallvors** [comment]
Benefits of the new model:
* Less code duplication
* Uses built-in Backbone model features for Ajax - we reduce the amount of code by removing the jQuery-dependency and $.ajax() calls for sending labels back to the server
* One single location to change things like the regexp recognising label prefixes
* Clear API for translating back and forth between prefixed and unprefixed labels, with code that is easier to read than the old approach
* Will hopefully through simplification fix #784 although I haven't debugged that in depth (that bug is why I'm working on the labels code in the first place..)

Regarding clicking label in /issues: I have not tested this yet, but I know I should. The idea is that instead of using labelsMap (which is part of the duplicated code) you would do something like 

```
 <a href="/issues/?q=label:<%= allLabels.toNamespaced(label.name) %>" class="wc-Labels" title="Labels : <%= label.name %>"><%= label.name %></a>
```
(or whatever the right URL for a label-specific search is) or handle it in the code which submits a query to the backend by calling the same method on a LabelList model instance there.

**Comment by miketaylr** [comment]
Cool.

> we reduce the amount of code by removing the jQuery-dependency and $.ajax() 

Backbone.sync/save/fetch use $.ajax in the background, IIRC. So we're just removing an explicit call rather than any real dependency.

> with code that is easier to read than the old approach

Ha, I guess that's subjective.

If you go down this route, please write (or update) corresponding Intern tests. There might also be some collisions around #712, depending on when that lands. :bomb:

**Comment by hallvors** [comment]
> I guess that's subjective
It most certainly is, but IMO for example this code could be more readable:
https://github.com/webcompat/webcompat.com/blob/5ca92e76aa8eee5ec63eabe641ced19565eac07d/webcompat/static/js/lib/models/issue.js#L204-L207

But fair enough - I *hope* it will be more readable :)

**Comment by miketaylr** [comment]
:smile:

**Comment by miketaylr** [comment]
+1 from me, thanks for proposing @hallvors! Let me know if you have any questions about some of the existing weird code or help w/ tests.
