### ISSUE TITLE
Add back image loader test

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#791]
Removed in https://github.com/webcompat/webcompat.com/commit/feb78b53d3fea4cef88dd1399fe5ea5a3263f466.

This needs to be re-written in such a way that a blazing fast fixture response (like 2 or 3ms) won't make it fail.

**Comment by hallvors** [comment]
The test should check if the class name of the loading indicator matches whether the page content is loaded yet or not. For example something like 

    var expected = document.querySelectorAll('p.wc-IssueItem-header a').length > 0 ? '' : 'is_active'

and assert className === expected. (If the first check results in is_active you might consider adding a findByCssSelector for the same selector and when it returns check that className is no longer is_active - due to timing issues that second test won't always run though).

**Comment by brizental** [comment]
So, I investigated this a little bit. At first I thought that we didn't have a loader for the search page, but we actually do, the code for it is just not working right now (https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L360).

There are some issues discussing back loader images (#1529 , #746 , #1000 ) and I think it would be important to test them, but I guess it would be best to just wait for these other issues to close first.

**Comment by miketaylr** [comment]
This doesn't make sense anymore, given the way the loader will happen with the refactor. Let's close.
