### ISSUE TITLE
"Filter by popular labels" does nothing

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#792]
If you do a search that matches nothing, you get a list of ways you might want to improve your search. 

One of them is "filter by popular labels" with a small list of clickable labels. Nothing happens when you click them.

(Aside: it is a bit strange to suggest improving a search that matches nothing by "filtering" it further. Are those links meant to apply the labels as a filter to the existing search with no results??)

@miketaylr  @karlcow  @magsout @calexity - thoughts?

**Comment by miketaylr** [comment]
This used to work. 

So we can either fix it or kill it.

`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=bdlkfjdfkjf#`

Haha, well that's why. The q is hard-coded to what the bogus search was. Should be easy to fix.

As for "filter by", the wording is a bit misleading. We can change it to "See results for some popular labels" or similar.

**Comment by miketaylr** [comment]
Ah, looks like I forgot to update this when I invented the labelsMap thingy. I'll do a quick fix now so it's not broken, and @hallvors can change it to whatever the new LabelsList implementation looks like later.

**Comment by miketaylr** [comment]
Looks like I forgot to send a PR for this.
